#ifndef  _BAK_CFG_INF_H_
#define  _BAK_CFG_INF_H_

#if defined(STM32F10X_HD)
#define SAVE_FROM_SD			1
#endif

#define  BAK_INF_VALID_FLAG			0x76333030//acsii --> V115   //0xaa558761

#define  BAK_VALID_FLAG_ADDR			0
#define  BAK_BAUDRATE_ADDR				BAK_VALID_FLAG_ADDR + 4
#define  BAK_LANGUARY_ADDR				BAK_BAUDRATE_ADDR + 1
#define  BAK_MOV_SPEED_ADDR			BAK_LANGUARY_ADDR + 1
#define  BAK_MOV_DIST_ADDR				BAK_MOV_SPEED_ADDR + 2
#define  BAK_EXTRU_SPEED_ADDR		BAK_MOV_DIST_ADDR + 2
#define  BAK_MACHINE_TYPE_ADDR		BAK_EXTRU_SPEED_ADDR + 2
#define  BAK_SPRAYER_NUM_ADDR		BAK_MACHINE_TYPE_ADDR + 1
#define  BAK_FAN_SPEED_ADDR			BAK_SPRAYER_NUM_ADDR + 1
#define  BAK_FILE_SYS_ADDR				BAK_FAN_SPEED_ADDR + 1

//#define  BAK_TOUCH_ADJ_FLAG_ADDR		BAK_FILE_SYS_ADDR + 1
//#define  BAK_TOUCH_ADJ_XMAX_ADDR		BAK_TOUCH_ADJ_FLAG_ADDR + 1
//#define  BAK_TOUCH_ADJ_XMIN_ADDR		BAK_TOUCH_ADJ_XMAX_ADDR + 4
//#define  BAK_TOUCH_ADJ_YMAX_ADDR		BAK_TOUCH_ADJ_XMIN_ADDR + 4
//#define  BAK_TOUCH_ADJ_YMIN_ADDR		BAK_TOUCH_ADJ_YMAX_ADDR + 4

//#define  BAK_CUSTOM_PIC_ADDR			BAK_TOUCH_ADJ_YMIN_ADDR + 4

#define  BAK_BACKGROUND_COLOR_ADD							BAK_FILE_SYS_ADDR + 1
#define  BAK_TITIL_COLOR_ADD										BAK_BACKGROUND_COLOR_ADD + 4
#define  BAK_STATE_BACKGROUND_COLOR_ADD			BAK_TITIL_COLOR_ADD + 4
#define  BAK_STATE_TEXT_COLOR_ADD							BAK_STATE_BACKGROUND_COLOR_ADD + 4
#define  BAK_FILENAME_COLOR_ADD								BAK_STATE_TEXT_COLOR_ADD + 4
#define  BAK_FILENAME_BACKGROUND_COLOR_ADD		BAK_FILENAME_COLOR_ADD + 4
#define  BAK_PRINTINGSTATE_WORD_BACKGROUND_COLOR_ADD	BAK_FILENAME_BACKGROUND_COLOR_ADD + 4
#define  BAK_PRINTINGSTATE_WORD_COLOR_ADD							BAK_PRINTINGSTATE_WORD_BACKGROUND_COLOR_ADD + 4

#define  BAK_MOREITEM_PIC_CNT					BAK_PRINTINGSTATE_WORD_COLOR_ADD + 4
#define	 BAK_CUSTOM_BED_FLAG_ADDR			BAK_MOREITEM_PIC_CNT+1
#define	 BAK_BUTTON_3D_EFFECT_FLAG		BAK_CUSTOM_BED_FLAG_ADDR+1
#define	 BAK_FIRMWARETYPE_ADDR					BAK_BUTTON_3D_EFFECT_FLAG+1

#define	 BAK_PAUSE_XPOS_ADDR						BAK_FIRMWARETYPE_ADDR+1
#define	 BAK_PAUSE_YPOS_ADDR						BAK_PAUSE_XPOS_ADDR+2
#define	 BAK_PAUSE_ZADD_ADDR						BAK_PAUSE_YPOS_ADDR+2

#define	 BAK_FUNC1_DISPLAY_ADDR				BAK_PAUSE_ZADD_ADDR+2
#define	 BAK_FUNC2_DISPLAY_ADDR				BAK_FUNC1_DISPLAY_ADDR+1

//#define	 BAK_PREHEAT_SPRAYER1_TEMP_ADDR		BAK_FUNC2_DISPLAY_ADDR+1
//#define	 BAK_PREHEAT_SPRAYER2_TEMP_ADDR				BAK_PREHEAT_SPRAYER1_TEMP_ADDR+4
//#define	 BAK_PREHEAT_BED_TEMP_ADDR				BAK_PREHEAT_SPRAYER2_TEMP_ADDR+4
#define	 BAK_SPRAYER1_MAXTEMP_ADDR		BAK_FUNC2_DISPLAY_ADDR+1
//#define	 BAK_SPRAYER2_MAXTEMP_ADDR		BAK_SPRAYER1_MAXTEMP_ADDR+4
#define	 BAK_BED_MAXTEMP_ADDR					BAK_SPRAYER1_MAXTEMP_ADDR+2

#define	 BAK_FILAMENT_DET1_FLAG_ADDR					BAK_BED_MAXTEMP_ADDR+2
#define	 BAK_PRINT_FINISH_CLOASE_MACHINE_ADDR		BAK_FILAMENT_DET1_FLAG_ADDR+1
#define  BAK_PRINTING_MOREFUNC_CNT_ADDR					BAK_PRINT_FINISH_CLOASE_MACHINE_ADDR+1

#define BAK_FILAMENT_LOAD_SPEED_ADDR			BAK_PRINTING_MOREFUNC_CNT_ADDR+2
#define BAK_FILAMENT_UNLOAD_SPEED_ADDR		BAK_FILAMENT_LOAD_SPEED_ADDR+2
#define BAK_FILAMENT_LOAD_LENGTH_ADDR			BAK_FILAMENT_UNLOAD_SPEED_ADDR+2
#define BAK_FILAMENT_UNLOAD_LENGTH_ADDR	BAK_FILAMENT_LOAD_LENGTH_ADDR+2
#define BAK_FILAMENT_LIMIT_TERMPER_ADDR 	BAK_FILAMENT_UNLOAD_LENGTH_ADDR+2
#define BAK_LEVELING_POINT_NUMBER_ADDR		BAK_FILAMENT_LIMIT_TERMPER_ADDR+2
#define BAK_LEVELING_POINT1_X_ADDR				BAK_LEVELING_POINT_NUMBER_ADDR+2
#define BAK_LEVELING_POINT1_Y_ADDR				BAK_LEVELING_POINT1_X_ADDR+2
#define BAK_LEVELING_POINT2_X_ADDR				BAK_LEVELING_POINT1_Y_ADDR+2
#define BAK_LEVELING_POINT2_Y_ADDR				BAK_LEVELING_POINT2_X_ADDR+2
#define BAK_LEVELING_POINT3_X_ADDR				BAK_LEVELING_POINT2_Y_ADDR+2
#define BAK_LEVELING_POINT3_Y_ADDR				BAK_LEVELING_POINT3_X_ADDR+2
#define BAK_LEVELING_POINT4_X_ADDR				BAK_LEVELING_POINT3_Y_ADDR+2
#define BAK_LEVELING_POINT4_Y_ADDR				BAK_LEVELING_POINT4_X_ADDR+2
#define BAK_LEVELING_POINT5_X_ADDR				BAK_LEVELING_POINT4_Y_ADDR+2
#define BAK_LEVELING_POINT5_Y_ADDR				BAK_LEVELING_POINT5_X_ADDR+2
#define BAK_LEVELING_Z_SPEED_ADDR				BAK_LEVELING_POINT5_Y_ADDR+2
#define BAK_LEVELING_XY_SPEED_ADDR				BAK_LEVELING_Z_SPEED_ADDR+2
#define BAK_PWROFF_SAVE_MODE_ADDR				BAK_LEVELING_XY_SPEED_ADDR+2
#define BAK_BREAKPOINT_Z_ERROR_ADDR			BAK_PWROFF_SAVE_MODE_ADDR+2
#define BAK_AUTOLEVELING_DISPLAY_ADDR		BAK_BREAKPOINT_Z_ERROR_ADDR+4
#define BAK_FILAMENT_DET2_FLAG_ADDR			BAK_AUTOLEVELING_DISPLAY_ADDR+1
#define BAK_HAVE_UPS_ADDR								BAK_FILAMENT_DET2_FLAG_ADDR+1
#define BAK_INSERT_MODULE_ADDR					BAK_HAVE_UPS_ADDR+1
#define BAK_LEVELING_MODE_ADDR					BAK_INSERT_MODULE_ADDR+1			
#define BAK_MULTIPLE_LANGUAGE_ADDR					BAK_LEVELING_MODE_ADDR+1
//#define BAK_DISABLE_PWR_DET_ADDR					BAK_MULTIPLE_LANGUAGE_ADDR+1
//#define BAK_DISABLE_MT_DET_ADDR					BAK_DISABLE_PWR_DET_ADDR+1

//2017.10.10
#define BAK_OVERTURN_180_ADDR                                  BAK_MULTIPLE_LANGUAGE_ADDR+1
#define BAK_LEVELING_Z_HIGH                                         BAK_OVERTURN_180_ADDR+1
//HC 2018.2.25
#define BAK_DISABLE_PWR_DET_ADDR                            BAK_LEVELING_Z_HIGH+2
#define BAK_DISABLE_MT_DET_ADDR                               BAK_DISABLE_PWR_DET_ADDR+1
#define BAK_SINGLE_NOZZLE_ADDR                                  BAK_DISABLE_MT_DET_ADDR+1
#define BAK_WIFI_STATE_ADDR                                        BAK_SINGLE_NOZZLE_ADDR+1
#define BAK_CLOUD_FLAG_ADDR                                       BAK_WIFI_STATE_ADDR+1
#define BAK_M110_ADD_CHECKSUM_ADDR                       BAK_CLOUD_FLAG_ADDR+1
#define BAK_DISP_EEROR_ADDR                                        BAK_M110_ADD_CHECKSUM_ADDR+1
#define BAK_UNLOAD_RETRACT_LENGTH_ADDR                 BAK_DISP_EEROR_ADDR+1
#define BAK_UNLOAD_RETRACT_SPEED_ADDR                   BAK_UNLOAD_RETRACT_LENGTH_ADDR+2
#define BAK_BABYSTEP_ADDR                  BAK_UNLOAD_RETRACT_SPEED_ADDR + 2	


#define  BAK_FILE_PATH_LEN_ADDR			BAK_BABYSTEP_ADDR + 1				
#define  BAK_FILE_PATH_ADDR				BAK_FILE_PATH_LEN_ADDR + 1				




typedef enum
{
	BAK_BAUD_ID,
	BAK_LANG_ID,
	BAK_MOV_SPEED_ID,
	BAK_MOV_DIST_ID,
	BAK_EXTRU_SPEED_ID,
	BAK_MACH_TYPE_ID,
	BAK_SPRAY_NUM_ID,
	BAK_FAN_SPEED_ID,
	BAK_FILE_SYS_ID,
	BAK_TOUCH_ADJ_FLAG_ID,
	BAK_TOUCH_ADJ_XMAX_ID,
	BAK_TOUCH_ADJ_XMIN_ID,
	BAK_TOUCH_ADJ_YMAX_ID,
	BAK_TOUCH_ADJ_YMIN_ID,
	BAK_CUSTOM_PIC_ID,
} BAK_INF_ITEM_ID;


extern void recover_cfg_inf(void);
extern void bakup_cfg_inf(BAK_INF_ITEM_ID  cfgItemId, uint32_t  value);
extern void bakup_file_path(uint8_t *path, uint32_t  len);
#endif

