#ifndef _SD_USR_H_
#define _SD_USR_H_


//flash信息有效的标志
#define FLASH_INF_VALID_FLAG			0xaa558761
#if defined(STM32F10X_HD)//2.4寸
//SD卡在flash中存储块的首地址
#define	SD_INF_ADDR		0X000000//
#endif

#if defined(STM32F10X_CL)//2.8~3.2寸
//SD卡在flash中存储块的首地址
#define	SD_INF_ADDR		0x1f9000//0X1AB000//
#endif
//SD卡在flash中信息有效标志存储地址
#define FlASH_INF_VALID_ADDR	SD_INF_ADDR
//更多菜单flash地址
#define BUTTON_CMD1_ADDR	FlASH_INF_VALID_ADDR+4
#define BUTTON_CMD2_ADDR	BUTTON_CMD1_ADDR+201
#define BUTTON_CMD3_ADDR	BUTTON_CMD2_ADDR+201
#define BUTTON_CMD4_ADDR	BUTTON_CMD3_ADDR+201
#define BUTTON_CMD5_ADDR	BUTTON_CMD4_ADDR+201
#define BUTTON_CMD6_ADDR	BUTTON_CMD5_ADDR+201
#define BUTTON_CMD7_ADDR	BUTTON_CMD6_ADDR+201
//wifi的flash地址
#define WIFI_NAME_ADDR		BUTTON_CMD7_ADDR+201
#define WIFI_KEYCODE_ADDR	WIFI_NAME_ADDR+201
#define WIFI_IP_ADDR		WIFI_KEYCODE_ADDR+201
#define WIFI_MASK_ADDR		WIFI_IP_ADDR+16
#define	WIFI_GATE_ADDR		WIFI_MASK_ADDR+16
#define	WIFI_DHCP_FLAG_ADDR	WIFI_GATE_ADDR+16
#define WIFI_MODE_SEL_ADDR	WIFI_DHCP_FLAG_ADDR+1
#define WIFI_AP_START_IP_ADDR	WIFI_MODE_SEL_ADDR+1
#define WIFI_AP_END_IP_ADDR		WIFI_AP_START_IP_ADDR+16
#define WIFI_DNS_ADDR			WIFI_AP_END_IP_ADDR+16
//功能键flash地址
#define BUTTON_FUNCTION1_ADDR	WIFI_DNS_ADDR+201
#define BUTTON_FUNCTION2_ADDR	BUTTON_FUNCTION1_ADDR+201
//打印界面更多菜单flash地址
#define BUTTON_MOREFUNC1_ADDR		BUTTON_FUNCTION2_ADDR+201
#define BUTTON_MOREFUNC2_ADDR		BUTTON_MOREFUNC1_ADDR+201
#define BUTTON_MOREFUNC3_ADDR		BUTTON_MOREFUNC2_ADDR+201
#define BUTTON_MOREFUNC4_ADDR		BUTTON_MOREFUNC3_ADDR+201
#define BUTTON_MOREFUNC5_ADDR		BUTTON_MOREFUNC4_ADDR+201
#define BUTTON_MOREFUNC6_ADDR		BUTTON_MOREFUNC5_ADDR+201
//自动调平指令存储地址
#define BUTTON_AUTOLEVELING_ADDR		BUTTON_MOREFUNC6_ADDR+201

#define WIFI_MODE_TYPE_ADDR	BUTTON_AUTOLEVELING_ADDR+201

extern uint32_t Sd_file_offset;
extern uint32_t Sd_file_cnt;
//extern uint32_t Sd_display_file_cnt;

extern void ShowSDFiles(void);

#endif

