/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: bmp_simple_sel
* Dimensions:  80 * 50
* NumColors:   256
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsbmp_simple_sel[] = {
     0x000000,0x000024,0x000048,0x00006D
    ,0x000091,0x0000B6,0x0000DA,0x0000FF
    ,0x005500,0x005524,0x005548,0x00556D
    ,0x005591,0x0055B6,0x0055DA,0x0055FF
    ,0x00AA00,0x00AA24,0x00AA48,0x00AA6D
    ,0x00AA91,0x00AAB6,0x00AADA,0x00AAFF
    ,0x00FF00,0x00FF24,0x00FF48,0x00FF6D
    ,0x00FF91,0x00FFB6,0x00FFDA,0x00FFFF
    ,0x240000,0x240024,0x240048,0x24006D
    ,0x240091,0x2400B6,0x2400DA,0x2400FF
    ,0x245500,0x245524,0x245548,0x24556D
    ,0x245591,0x2455B6,0x2455DA,0x2455FF
    ,0x24AA00,0x24AA24,0x24AA48,0x24AA6D
    ,0x24AA91,0x24AAB6,0x24AADA,0x24AAFF
    ,0x24FF00,0x24FF24,0x24FF48,0x24FF6D
    ,0x24FF91,0x24FFB6,0x24FFDA,0x24FFFF
    ,0x480000,0x480024,0x480048,0x48006D
    ,0x480091,0x4800B6,0x4800DA,0x4800FF
    ,0x485500,0x485524,0x485548,0x48556D
    ,0x485591,0x4855B6,0x4855DA,0x4855FF
    ,0x48AA00,0x48AA24,0x48AA48,0x48AA6D
    ,0x48AA91,0x48AAB6,0x48AADA,0x48AAFF
    ,0x48FF00,0x48FF24,0x48FF48,0x48FF6D
    ,0x48FF91,0x48FFB6,0x48FFDA,0x48FFFF
    ,0x6D0000,0x6D0024,0x6D0048,0x6D006D
    ,0x6D0091,0x6D00B6,0x6D00DA,0x6D00FF
    ,0x6D5500,0x6D5524,0x6D5548,0x6D556D
    ,0x6D5591,0x6D55B6,0x6D55DA,0x6D55FF
    ,0x6DAA00,0x6DAA24,0x6DAA48,0x6DAA6D
    ,0x6DAA91,0x6DAAB6,0x6DAADA,0x6DAAFF
    ,0x6DFF00,0x6DFF24,0x6DFF48,0x6DFF6D
    ,0x6DFF91,0x6DFFB6,0x6DFFDA,0x6DFFFF
    ,0x910000,0x910024,0x910048,0x91006D
    ,0x910091,0x9100B6,0x9100DA,0x9100FF
    ,0x915500,0x915524,0x915548,0x91556D
    ,0x915591,0x9155B6,0x9155DA,0x9155FF
    ,0x91AA00,0x91AA24,0x91AA48,0x91AA6D
    ,0x91AA91,0x91AAB6,0x91AADA,0x91AAFF
    ,0x91FF00,0x91FF24,0x91FF48,0x91FF6D
    ,0x91FF91,0x91FFB6,0x91FFDA,0x91FFFF
    ,0xB60000,0xB60024,0xB60048,0xB6006D
    ,0xB60091,0xB600B6,0xB600DA,0xB600FF
    ,0xB65500,0xB65524,0xB65548,0xB6556D
    ,0xB65591,0xB655B6,0xB655DA,0xB655FF
    ,0xB6AA00,0xB6AA24,0xB6AA48,0xB6AA6D
    ,0xB6AA91,0xB6AAB6,0xB6AADA,0xB6AAFF
    ,0xB6FF00,0xB6FF24,0xB6FF48,0xB6FF6D
    ,0xB6FF91,0xB6FFB6,0xB6FFDA,0xB6FFFF
    ,0xDA0000,0xDA0024,0xDA0048,0xDA006D
    ,0xDA0091,0xDA00B6,0xDA00DA,0xDA00FF
    ,0xDA5500,0xDA5524,0xDA5548,0xDA556D
    ,0xDA5591,0xDA55B6,0xDA55DA,0xDA55FF
    ,0xDAAA00,0xDAAA24,0xDAAA48,0xDAAA6D
    ,0xDAAA91,0xDAAAB6,0xDAAADA,0xDAAAFF
    ,0xDAFF00,0xDAFF24,0xDAFF48,0xDAFF6D
    ,0xDAFF91,0xDAFFB6,0xDAFFDA,0xDAFFFF
    ,0xFF0000,0xFF0024,0xFF0048,0xFF006D
    ,0xFF0091,0xFF00B6,0xFF00DA,0xFF00FF
    ,0xFF5500,0xFF5524,0xFF5548,0xFF556D
    ,0xFF5591,0xFF55B6,0xFF55DA,0xFF55FF
    ,0xFFAA00,0xFFAA24,0xFFAA48,0xFFAA6D
    ,0xFFAA91,0xFFAAB6,0xFFAADA,0xFFAAFF
    ,0xFFFF00,0xFFFF24,0xFFFF48,0xFFFF6D
    ,0xFFFF91,0xFFFFB6,0xFFFFDA,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palbmp_simple_sel = {
  256,	/* number of entries */
  0, 	/* No transparency */
  &Colorsbmp_simple_sel[0]
};

static GUI_CONST_STORAGE unsigned char acbmp_simple_sel[] = {
  /* RLE: 749 Pixels @ 000,000*/ 254, 0x10, 254, 0x10, 241, 0x10, 
  /* RLE: 005 Pixels @ 029,009*/ 5, 0xFF, 
  /* RLE: 007 Pixels @ 034,009*/ 7, 0x10, 
  /* RLE: 005 Pixels @ 041,009*/ 5, 0xFF, 
  /* RLE: 062 Pixels @ 046,009*/ 62, 0x10, 
  /* RLE: 007 Pixels @ 028,010*/ 7, 0xFF, 
  /* RLE: 005 Pixels @ 035,010*/ 5, 0x10, 
  /* RLE: 003 Pixels @ 040,010*/ 3, 0xFF, 
  /* ABS: 004 Pixels @ 043,010*/ 0, 4, 0x10, 0xFF, 0xFF, 0xFF, 
  /* RLE: 060 Pixels @ 047,010*/ 60, 0x10, 
  /* RLE: 003 Pixels @ 027,011*/ 3, 0xFF, 
  /* RLE: 004 Pixels @ 030,011*/ 4, 0x10, 
  /* RLE: 008 Pixels @ 034,011*/ 8, 0xFF, 
  /* RLE: 004 Pixels @ 042,011*/ 4, 0x10, 
  /* RLE: 007 Pixels @ 046,011*/ 7, 0xFF, 
  /* RLE: 054 Pixels @ 053,011*/ 54, 0x10, 
  /* ABS: 002 Pixels @ 027,012*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 029,012*/ 5, 0x10, 
  /* RLE: 008 Pixels @ 034,012*/ 8, 0xFF, 
  /* RLE: 004 Pixels @ 042,012*/ 4, 0x10, 
  /* RLE: 008 Pixels @ 046,012*/ 8, 0xFF, 
  /* RLE: 052 Pixels @ 054,012*/ 52, 0x10, 
  /* ABS: 002 Pixels @ 026,013*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 028,013*/ 11, 0x10, 
  /* ABS: 002 Pixels @ 039,013*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 041,013*/ 11, 0x10, 
  /* ABS: 002 Pixels @ 052,013*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 051 Pixels @ 054,013*/ 51, 0x10, 
  /* RLE: 003 Pixels @ 025,014*/ 3, 0xFF, 
  /* RLE: 010 Pixels @ 028,014*/ 10, 0x10, 
  /* RLE: 003 Pixels @ 038,014*/ 3, 0xFF, 
  /* RLE: 011 Pixels @ 041,014*/ 11, 0x10, 
  /* ABS: 002 Pixels @ 052,014*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 051 Pixels @ 054,014*/ 51, 0x10, 
  /* ABS: 002 Pixels @ 025,015*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 027,015*/ 11, 0x10, 
  /* ABS: 002 Pixels @ 038,015*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 012 Pixels @ 040,015*/ 12, 0x10, 
  /* ABS: 002 Pixels @ 052,015*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 050 Pixels @ 054,015*/ 50, 0x10, 
  /* ABS: 002 Pixels @ 024,016*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 010 Pixels @ 026,016*/ 10, 0x10, 
  /* RLE: 004 Pixels @ 036,016*/ 4, 0xFF, 
  /* RLE: 009 Pixels @ 040,016*/ 9, 0x10, 
  /* RLE: 005 Pixels @ 049,016*/ 5, 0xFF, 
  /* RLE: 050 Pixels @ 054,016*/ 50, 0x10, 
  /* ABS: 002 Pixels @ 024,017*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 026,017*/ 5, 0x10, 
  /* ABS: 005 Pixels @ 031,017*/ 0, 5, 0xFF, 0xFF, 0x10, 0x10, 0x10, 
  /* RLE: 004 Pixels @ 036,017*/ 4, 0xFF, 
  /* RLE: 004 Pixels @ 040,017*/ 4, 0x10, 
  /* ABS: 005 Pixels @ 044,017*/ 0, 5, 0xFF, 0xFF, 0x10, 0x10, 0x10, 
  /* RLE: 004 Pixels @ 049,017*/ 4, 0xFF, 
  /* RLE: 051 Pixels @ 053,017*/ 51, 0x10, 
  /* ABS: 002 Pixels @ 024,018*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 026,018*/ 5, 0x10, 
  /* ABS: 005 Pixels @ 031,018*/ 0, 5, 0xFF, 0xFF, 0x10, 0x10, 0x10, 
  /* RLE: 005 Pixels @ 036,018*/ 5, 0xFF, 
  /* ABS: 008 Pixels @ 041,018*/ 0, 8, 0x10, 0x10, 0xFF, 0xFF, 0xFF, 0x10, 0x10, 0x10, 
  /* RLE: 004 Pixels @ 049,018*/ 4, 0xFF, 
  /* RLE: 052 Pixels @ 053,018*/ 52, 0x10, 
  /* RLE: 003 Pixels @ 025,019*/ 3, 0xFF, 
  /* ABS: 002 Pixels @ 028,019*/ 0, 2, 0x10, 0x10, 
  /* RLE: 008 Pixels @ 030,019*/ 8, 0xFF, 
  /* ABS: 002 Pixels @ 038,019*/ 0, 2, 0x10, 0x10, 
  /* RLE: 004 Pixels @ 040,019*/ 4, 0xFF, 
  /* RLE: 001 Pixels @ 044,019*/ 1, 0x10, 
  /* RLE: 005 Pixels @ 045,019*/ 5, 0xFF, 
  /* ABS: 003 Pixels @ 050,019*/ 0, 3, 0x10, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,019*/ 53, 0x10, 
  /* RLE: 005 Pixels @ 026,020*/ 5, 0xFF, 
  /* ABS: 002 Pixels @ 031,020*/ 0, 2, 0x10, 0x10, 
  /* RLE: 005 Pixels @ 033,020*/ 5, 0xFF, 
  /* RLE: 008 Pixels @ 038,020*/ 8, 0x10, 
  /* ABS: 007 Pixels @ 046,020*/ 0, 7, 0xFF, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0xFF, 
  /* RLE: 054 Pixels @ 053,020*/ 54, 0x10, 
  /* RLE: 005 Pixels @ 027,021*/ 5, 0xFF, 
  /* RLE: 004 Pixels @ 032,021*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 036,021*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 013 Pixels @ 038,021*/ 13, 0x10, 
  /* ABS: 002 Pixels @ 051,021*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,021*/ 53, 0x10, 
  /* RLE: 021 Pixels @ 026,022*/ 21, 0xFF, 
  /* RLE: 004 Pixels @ 047,022*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 051,022*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,022*/ 53, 0x10, 
  /* ABS: 002 Pixels @ 026,023*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 028,023*/ 4, 0x10, 
  /* RLE: 015 Pixels @ 032,023*/ 15, 0xFF, 
  /* RLE: 004 Pixels @ 047,023*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 051,023*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,023*/ 53, 0x10, 
  /* ABS: 002 Pixels @ 026,024*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 028,024*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 032,024*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 034,024*/ 11, 0x10, 
  /* ABS: 002 Pixels @ 045,024*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 047,024*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 051,024*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,024*/ 53, 0x10, 
  /* ABS: 002 Pixels @ 026,025*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 028,025*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 032,025*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 034,025*/ 11, 0x10, 
  /* ABS: 002 Pixels @ 045,025*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 047,025*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 051,025*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,025*/ 53, 0x10, 
  /* ABS: 002 Pixels @ 026,026*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 028,026*/ 4, 0x10, 
  /* ABS: 005 Pixels @ 032,026*/ 0, 5, 0xFF, 0xFF, 0x10, 0x10, 0x10, 
  /* RLE: 005 Pixels @ 037,026*/ 5, 0xFF, 
  /* RLE: 003 Pixels @ 042,026*/ 3, 0x10, 
  /* ABS: 002 Pixels @ 045,026*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 047,026*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 051,026*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,026*/ 53, 0x10, 
  /* ABS: 002 Pixels @ 026,027*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 028,027*/ 4, 0x10, 
  /* ABS: 005 Pixels @ 032,027*/ 0, 5, 0xFF, 0xFF, 0x10, 0x10, 0x10, 
  /* RLE: 005 Pixels @ 037,027*/ 5, 0xFF, 
  /* RLE: 003 Pixels @ 042,027*/ 3, 0x10, 
  /* ABS: 002 Pixels @ 045,027*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 047,027*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 051,027*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,027*/ 53, 0x10, 
  /* ABS: 002 Pixels @ 026,028*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 028,028*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 032,028*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 034,028*/ 11, 0x10, 
  /* ABS: 002 Pixels @ 045,028*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 047,028*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 051,028*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,028*/ 53, 0x10, 
  /* ABS: 002 Pixels @ 026,029*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 028,029*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 032,029*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 034,029*/ 11, 0x10, 
  /* ABS: 002 Pixels @ 045,029*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 047,029*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 051,029*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,029*/ 53, 0x10, 
  /* ABS: 002 Pixels @ 026,030*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 028,030*/ 4, 0x10, 
  /* ABS: 005 Pixels @ 032,030*/ 0, 5, 0xFF, 0xFF, 0x10, 0x10, 0x10, 
  /* RLE: 005 Pixels @ 037,030*/ 5, 0xFF, 
  /* RLE: 003 Pixels @ 042,030*/ 3, 0x10, 
  /* ABS: 002 Pixels @ 045,030*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 047,030*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 051,030*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,030*/ 53, 0x10, 
  /* ABS: 002 Pixels @ 026,031*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 028,031*/ 4, 0x10, 
  /* ABS: 005 Pixels @ 032,031*/ 0, 5, 0xFF, 0xFF, 0x10, 0x10, 0x10, 
  /* RLE: 005 Pixels @ 037,031*/ 5, 0xFF, 
  /* RLE: 003 Pixels @ 042,031*/ 3, 0x10, 
  /* ABS: 002 Pixels @ 045,031*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 047,031*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 051,031*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,031*/ 53, 0x10, 
  /* ABS: 002 Pixels @ 026,032*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 028,032*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 032,032*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 009 Pixels @ 034,032*/ 9, 0x10, 
  /* RLE: 004 Pixels @ 043,032*/ 4, 0xFF, 
  /* RLE: 004 Pixels @ 047,032*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 051,032*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,032*/ 53, 0x10, 
  /* ABS: 002 Pixels @ 026,033*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 028,033*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 032,033*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 034,033*/ 8, 0x10, 
  /* RLE: 005 Pixels @ 042,033*/ 5, 0xFF, 
  /* RLE: 004 Pixels @ 047,033*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 051,033*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,033*/ 53, 0x10, 
  /* ABS: 002 Pixels @ 026,034*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 028,034*/ 4, 0x10, 
  /* RLE: 003 Pixels @ 032,034*/ 3, 0xFF, 
  /* RLE: 007 Pixels @ 035,034*/ 7, 0x10, 
  /* ABS: 002 Pixels @ 042,034*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 044,034*/ 7, 0x10, 
  /* ABS: 002 Pixels @ 051,034*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,034*/ 53, 0x10, 
  /* ABS: 002 Pixels @ 026,035*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 028,035*/ 4, 0x10, 
  /* RLE: 012 Pixels @ 032,035*/ 12, 0xFF, 
  /* RLE: 007 Pixels @ 044,035*/ 7, 0x10, 
  /* ABS: 002 Pixels @ 051,035*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,035*/ 53, 0x10, 
  /* ABS: 002 Pixels @ 026,036*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 028,036*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 032,036*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 034,036*/ 8, 0x10, 
  /* ABS: 002 Pixels @ 042,036*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 044,036*/ 7, 0x10, 
  /* ABS: 002 Pixels @ 051,036*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,036*/ 53, 0x10, 
  /* ABS: 002 Pixels @ 026,037*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 028,037*/ 4, 0x10, 
  /* ABS: 002 Pixels @ 032,037*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 034,037*/ 8, 0x10, 
  /* ABS: 002 Pixels @ 042,037*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 044,037*/ 7, 0x10, 
  /* ABS: 002 Pixels @ 051,037*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 053 Pixels @ 053,037*/ 53, 0x10, 
  /* RLE: 008 Pixels @ 026,038*/ 8, 0xFF, 
  /* RLE: 009 Pixels @ 034,038*/ 9, 0x10, 
  /* RLE: 010 Pixels @ 043,038*/ 10, 0xFF, 
  /* RLE: 054 Pixels @ 053,038*/ 54, 0x10, 
  /* RLE: 006 Pixels @ 027,039*/ 6, 0xFF, 
  /* RLE: 011 Pixels @ 033,039*/ 11, 0x10, 
  /* RLE: 007 Pixels @ 044,039*/ 7, 0xFF, 
  /* RLE: 829 Pixels @ 051,039*/ 254, 0x10, 254, 0x10, 254, 0x10, 67, 0x10, 


  0};  /* 627 for 4000 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmbmp_simple_sel = {
  80, /* XSize */
  50, /* YSize */
  80, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acbmp_simple_sel,  /* Pointer to picture data (indices) */
  &Palbmp_simple_sel  /* Pointer to palette */
 ,GUI_DRAW_RLE8
};

/* *** End of file *** */
