/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: bmp_menu
* Dimensions:  80 * 50
* NumColors:   256
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsbmp_menu[] = {
     0x000000,0x000024,0x000048,0x00006D
    ,0x000091,0x0000B6,0x0000DA,0x0000FF
    ,0x005500,0x005524,0x005548,0x00556D
    ,0x005591,0x0055B6,0x0055DA,0x0055FF
    ,0x00AA00,0x00AA24,0x00AA48,0x00AA6D
    ,0x00AA91,0x00AAB6,0x00AADA,0x00AAFF
    ,0x00FF00,0x00FF24,0x00FF48,0x00FF6D
    ,0x00FF91,0x00FFB6,0x00FFDA,0x00FFFF
    ,0x240000,0x240024,0x240048,0x24006D
    ,0x240091,0x2400B6,0x2400DA,0x2400FF
    ,0x245500,0x245524,0x245548,0x24556D
    ,0x245591,0x2455B6,0x2455DA,0x2455FF
    ,0x24AA00,0x24AA24,0x24AA48,0x24AA6D
    ,0x24AA91,0x24AAB6,0x24AADA,0x24AAFF
    ,0x24FF00,0x24FF24,0x24FF48,0x24FF6D
    ,0x24FF91,0x24FFB6,0x24FFDA,0x24FFFF
    ,0x480000,0x480024,0x480048,0x48006D
    ,0x480091,0x4800B6,0x4800DA,0x4800FF
    ,0x485500,0x485524,0x485548,0x48556D
    ,0x485591,0x4855B6,0x4855DA,0x4855FF
    ,0x48AA00,0x48AA24,0x48AA48,0x48AA6D
    ,0x48AA91,0x48AAB6,0x48AADA,0x48AAFF
    ,0x48FF00,0x48FF24,0x48FF48,0x48FF6D
    ,0x48FF91,0x48FFB6,0x48FFDA,0x48FFFF
    ,0x6D0000,0x6D0024,0x6D0048,0x6D006D
    ,0x6D0091,0x6D00B6,0x6D00DA,0x6D00FF
    ,0x6D5500,0x6D5524,0x6D5548,0x6D556D
    ,0x6D5591,0x6D55B6,0x6D55DA,0x6D55FF
    ,0x6DAA00,0x6DAA24,0x6DAA48,0x6DAA6D
    ,0x6DAA91,0x6DAAB6,0x6DAADA,0x6DAAFF
    ,0x6DFF00,0x6DFF24,0x6DFF48,0x6DFF6D
    ,0x6DFF91,0x6DFFB6,0x6DFFDA,0x6DFFFF
    ,0x910000,0x910024,0x910048,0x91006D
    ,0x910091,0x9100B6,0x9100DA,0x9100FF
    ,0x915500,0x915524,0x915548,0x91556D
    ,0x915591,0x9155B6,0x9155DA,0x9155FF
    ,0x91AA00,0x91AA24,0x91AA48,0x91AA6D
    ,0x91AA91,0x91AAB6,0x91AADA,0x91AAFF
    ,0x91FF00,0x91FF24,0x91FF48,0x91FF6D
    ,0x91FF91,0x91FFB6,0x91FFDA,0x91FFFF
    ,0xB60000,0xB60024,0xB60048,0xB6006D
    ,0xB60091,0xB600B6,0xB600DA,0xB600FF
    ,0xB65500,0xB65524,0xB65548,0xB6556D
    ,0xB65591,0xB655B6,0xB655DA,0xB655FF
    ,0xB6AA00,0xB6AA24,0xB6AA48,0xB6AA6D
    ,0xB6AA91,0xB6AAB6,0xB6AADA,0xB6AAFF
    ,0xB6FF00,0xB6FF24,0xB6FF48,0xB6FF6D
    ,0xB6FF91,0xB6FFB6,0xB6FFDA,0xB6FFFF
    ,0xDA0000,0xDA0024,0xDA0048,0xDA006D
    ,0xDA0091,0xDA00B6,0xDA00DA,0xDA00FF
    ,0xDA5500,0xDA5524,0xDA5548,0xDA556D
    ,0xDA5591,0xDA55B6,0xDA55DA,0xDA55FF
    ,0xDAAA00,0xDAAA24,0xDAAA48,0xDAAA6D
    ,0xDAAA91,0xDAAAB6,0xDAAADA,0xDAAAFF
    ,0xDAFF00,0xDAFF24,0xDAFF48,0xDAFF6D
    ,0xDAFF91,0xDAFFB6,0xDAFFDA,0xDAFFFF
    ,0xFF0000,0xFF0024,0xFF0048,0xFF006D
    ,0xFF0091,0xFF00B6,0xFF00DA,0xFF00FF
    ,0xFF5500,0xFF5524,0xFF5548,0xFF556D
    ,0xFF5591,0xFF55B6,0xFF55DA,0xFF55FF
    ,0xFFAA00,0xFFAA24,0xFFAA48,0xFFAA6D
    ,0xFFAA91,0xFFAAB6,0xFFAADA,0xFFAAFF
    ,0xFFFF00,0xFFFF24,0xFFFF48,0xFFFF6D
    ,0xFFFF91,0xFFFFB6,0xFFFFDA,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palbmp_menu = {
  256,	/* number of entries */
  0, 	/* No transparency */
  &Colorsbmp_menu[0]
};

static GUI_CONST_STORAGE unsigned char acbmp_menu[] = {
  /* RLE: 1009 Pixels @ 000,000*/ 254, 0x10, 254, 0x10, 254, 0x10, 247, 0x10, 
  /* ABS: 002 Pixels @ 049,012*/ 0, 2, 0x94, 0x94, 
  /* RLE: 061 Pixels @ 051,012*/ 61, 0x10, 
  /* RLE: 004 Pixels @ 032,013*/ 4, 0xFF, 
  /* RLE: 001 Pixels @ 036,013*/ 1, 0xB5, 
  /* RLE: 011 Pixels @ 037,013*/ 11, 0x10, 
  /* RLE: 003 Pixels @ 048,013*/ 3, 0xFF, 
  /* RLE: 001 Pixels @ 051,013*/ 1, 0xD6, 
  /* RLE: 061 Pixels @ 052,013*/ 61, 0x10, 
  /* RLE: 004 Pixels @ 033,014*/ 4, 0xFF, 
  /* RLE: 001 Pixels @ 037,014*/ 1, 0xD6, 
  /* RLE: 009 Pixels @ 038,014*/ 9, 0x10, 
  /* ABS: 006 Pixels @ 047,014*/ 0, 6, 0xFF, 0xB5, 0x10, 0xFF, 0xFF, 0xB5, 
  /* RLE: 061 Pixels @ 053,014*/ 61, 0x10, 
  /* RLE: 004 Pixels @ 034,015*/ 4, 0xFF, 
  /* RLE: 001 Pixels @ 038,015*/ 1, 0xB5, 
  /* RLE: 007 Pixels @ 039,015*/ 7, 0x10, 
  /* ABS: 007 Pixels @ 046,015*/ 0, 7, 0xFF, 0xB5, 0x10, 0xFF, 0xDE, 0xDE, 0xD6, 
  /* RLE: 062 Pixels @ 053,015*/ 62, 0x10, 
  /* RLE: 003 Pixels @ 035,016*/ 3, 0xFF, 
  /* RLE: 001 Pixels @ 038,016*/ 1, 0xDE, 
  /* RLE: 006 Pixels @ 039,016*/ 6, 0x10, 
  /* ABS: 008 Pixels @ 045,016*/ 0, 8, 0xFF, 0xB5, 0x10, 0xFF, 0xD6, 0x10, 0xDE, 0xB5, 
  /* RLE: 055 Pixels @ 053,016*/ 55, 0x10, 
  /* RLE: 001 Pixels @ 028,017*/ 1, 0xDE, 
  /* RLE: 006 Pixels @ 029,017*/ 6, 0x10, 
  /* ABS: 004 Pixels @ 035,017*/ 0, 4, 0xDE, 0xFF, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 039,017*/ 5, 0x10, 
  /* ABS: 008 Pixels @ 044,017*/ 0, 8, 0xFF, 0xB5, 0x10, 0xFF, 0xD6, 0x10, 0xDE, 0xDE, 
  /* RLE: 056 Pixels @ 052,017*/ 56, 0x10, 
  /* ABS: 002 Pixels @ 028,018*/ 0, 2, 0xFF, 0xDE, 
  /* RLE: 005 Pixels @ 030,018*/ 5, 0x10, 
  /* RLE: 004 Pixels @ 035,018*/ 4, 0xFF, 
  /* RLE: 004 Pixels @ 039,018*/ 4, 0x10, 
  /* ABS: 008 Pixels @ 043,018*/ 0, 8, 0xFF, 0xB5, 0x10, 0xFF, 0xD6, 0x10, 0xDE, 0xDE, 
  /* RLE: 057 Pixels @ 051,018*/ 57, 0x10, 
  /* ABS: 006 Pixels @ 028,019*/ 0, 6, 0xFF, 0xFF, 0xDE, 0x10, 0x10, 0x10, 
  /* RLE: 005 Pixels @ 034,019*/ 5, 0xFF, 
  /* RLE: 003 Pixels @ 039,019*/ 3, 0x10, 
  /* ABS: 008 Pixels @ 042,019*/ 0, 8, 0xFF, 0xB5, 0x10, 0xFF, 0xD6, 0x10, 0xDE, 0xDE, 
  /* RLE: 058 Pixels @ 050,019*/ 58, 0x10, 
  /* RLE: 004 Pixels @ 028,020*/ 4, 0xFF, 
  /* RLE: 001 Pixels @ 032,020*/ 1, 0xDE, 
  /* RLE: 007 Pixels @ 033,020*/ 7, 0xFF, 
  /* ABS: 009 Pixels @ 040,020*/ 0, 9, 0x10, 0x10, 0xB5, 0x10, 0xFF, 0xD6, 0x10, 0xDE, 0xDE, 
  /* RLE: 059 Pixels @ 049,020*/ 59, 0x10, 
  /* RLE: 001 Pixels @ 028,021*/ 1, 0xB5, 
  /* RLE: 012 Pixels @ 029,021*/ 12, 0xFF, 
  /* ABS: 007 Pixels @ 041,021*/ 0, 7, 0x10, 0x10, 0xDE, 0xD6, 0x10, 0xDE, 0xDE, 
  /* RLE: 061 Pixels @ 048,021*/ 61, 0x10, 
  /* RLE: 001 Pixels @ 029,022*/ 1, 0xD6, 
  /* RLE: 012 Pixels @ 030,022*/ 12, 0xFF, 
  /* RLE: 003 Pixels @ 042,022*/ 3, 0x10, 
  /* ABS: 002 Pixels @ 045,022*/ 0, 2, 0xDE, 0xDE, 
  /* RLE: 063 Pixels @ 047,022*/ 63, 0x10, 
  /* ABS: 002 Pixels @ 030,023*/ 0, 2, 0xB5, 0xDE, 
  /* RLE: 011 Pixels @ 032,023*/ 11, 0xFF, 
  /* ABS: 003 Pixels @ 043,023*/ 0, 3, 0x10, 0x10, 0xD6, 
  /* RLE: 069 Pixels @ 046,023*/ 69, 0x10, 
  /* RLE: 009 Pixels @ 035,024*/ 9, 0xFF, 
  /* RLE: 072 Pixels @ 044,024*/ 72, 0x10, 
  /* RLE: 009 Pixels @ 036,025*/ 9, 0xFF, 
  /* RLE: 072 Pixels @ 045,025*/ 72, 0x10, 
  /* RLE: 009 Pixels @ 037,026*/ 9, 0xFF, 
  /* RLE: 072 Pixels @ 046,026*/ 72, 0x10, 
  /* RLE: 009 Pixels @ 038,027*/ 9, 0xFF, 
  /* RLE: 068 Pixels @ 047,027*/ 68, 0x10, 
  /* ABS: 004 Pixels @ 035,028*/ 0, 4, 0xB5, 0xDE, 0x10, 0x10, 
  /* RLE: 009 Pixels @ 039,028*/ 9, 0xFF, 
  /* RLE: 066 Pixels @ 048,028*/ 66, 0x10, 
  /* ABS: 006 Pixels @ 034,029*/ 0, 6, 0xB5, 0xFF, 0xFF, 0x10, 0x10, 0x10, 
  /* RLE: 009 Pixels @ 040,029*/ 9, 0xFF, 
  /* RLE: 064 Pixels @ 049,029*/ 64, 0x10, 
  /* ABS: 003 Pixels @ 033,030*/ 0, 3, 0xB5, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 036,030*/ 5, 0x10, 
  /* RLE: 009 Pixels @ 041,030*/ 9, 0xFF, 
  /* RLE: 062 Pixels @ 050,030*/ 62, 0x10, 
  /* ABS: 003 Pixels @ 032,031*/ 0, 3, 0xB5, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 035,031*/ 7, 0x10, 
  /* RLE: 009 Pixels @ 042,031*/ 9, 0xFF, 
  /* RLE: 060 Pixels @ 051,031*/ 60, 0x10, 
  /* RLE: 003 Pixels @ 031,032*/ 3, 0xFF, 
  /* RLE: 009 Pixels @ 034,032*/ 9, 0x10, 
  /* RLE: 005 Pixels @ 043,032*/ 5, 0xFF, 
  /* ABS: 004 Pixels @ 048,032*/ 0, 4, 0xDE, 0xB5, 0xFF, 0xFF, 
  /* RLE: 058 Pixels @ 052,032*/ 58, 0x10, 
  /* RLE: 003 Pixels @ 030,033*/ 3, 0xFF, 
  /* RLE: 011 Pixels @ 033,033*/ 11, 0x10, 
  /* RLE: 003 Pixels @ 044,033*/ 3, 0xFF, 
  /* ABS: 006 Pixels @ 047,033*/ 0, 6, 0xD6, 0x10, 0x10, 0x10, 0xFF, 0xB5, 
  /* RLE: 056 Pixels @ 053,033*/ 56, 0x10, 
  /* RLE: 003 Pixels @ 029,034*/ 3, 0xFF, 
  /* RLE: 013 Pixels @ 032,034*/ 13, 0x10, 
  /* ABS: 008 Pixels @ 045,034*/ 0, 8, 0xFF, 0xFF, 0xB5, 0x10, 0x10, 0x10, 0xDE, 0xB5, 
  /* RLE: 055 Pixels @ 053,034*/ 55, 0x10, 
  /* ABS: 003 Pixels @ 028,035*/ 0, 3, 0xD6, 0xFF, 0xFF, 
  /* RLE: 015 Pixels @ 031,035*/ 15, 0x10, 
  /* ABS: 007 Pixels @ 046,035*/ 0, 7, 0xFF, 0xDE, 0x10, 0x10, 0x10, 0xFF, 0x94, 
  /* RLE: 055 Pixels @ 053,035*/ 55, 0x10, 
  /* ABS: 002 Pixels @ 028,036*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 017 Pixels @ 030,036*/ 17, 0x10, 
  /* ABS: 005 Pixels @ 047,036*/ 0, 5, 0xFF, 0xDE, 0xDE, 0xFF, 0xD6, 
  /* RLE: 076 Pixels @ 052,036*/ 76, 0x10, 
  /* ABS: 002 Pixels @ 048,037*/ 0, 2, 0xB5, 0xD6, 
  /* RLE: 990 Pixels @ 050,037*/ 254, 0x10, 254, 0x10, 254, 0x10, 228, 0x10, 


  0};  /* 357 for 4000 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmbmp_menu = {
  80, /* XSize */
  50, /* YSize */
  80, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acbmp_menu,  /* Pointer to picture data (indices) */
  &Palbmp_menu  /* Pointer to palette */
 ,GUI_DRAW_RLE8
};

/* *** End of file *** */
