/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: bmp_speed127
* Dimensions:  80 * 50
* NumColors:   256
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsbmp_speed127[] = {
     0x000000,0x000024,0x000048,0x00006D
    ,0x000091,0x0000B6,0x0000DA,0x0000FF
    ,0x005500,0x005524,0x005548,0x00556D
    ,0x005591,0x0055B6,0x0055DA,0x0055FF
    ,0x00AA00,0x00AA24,0x00AA48,0x00AA6D
    ,0x00AA91,0x00AAB6,0x00AADA,0x00AAFF
    ,0x00FF00,0x00FF24,0x00FF48,0x00FF6D
    ,0x00FF91,0x00FFB6,0x00FFDA,0x00FFFF
    ,0x240000,0x240024,0x240048,0x24006D
    ,0x240091,0x2400B6,0x2400DA,0x2400FF
    ,0x245500,0x245524,0x245548,0x24556D
    ,0x245591,0x2455B6,0x2455DA,0x2455FF
    ,0x24AA00,0x24AA24,0x24AA48,0x24AA6D
    ,0x24AA91,0x24AAB6,0x24AADA,0x24AAFF
    ,0x24FF00,0x24FF24,0x24FF48,0x24FF6D
    ,0x24FF91,0x24FFB6,0x24FFDA,0x24FFFF
    ,0x480000,0x480024,0x480048,0x48006D
    ,0x480091,0x4800B6,0x4800DA,0x4800FF
    ,0x485500,0x485524,0x485548,0x48556D
    ,0x485591,0x4855B6,0x4855DA,0x4855FF
    ,0x48AA00,0x48AA24,0x48AA48,0x48AA6D
    ,0x48AA91,0x48AAB6,0x48AADA,0x48AAFF
    ,0x48FF00,0x48FF24,0x48FF48,0x48FF6D
    ,0x48FF91,0x48FFB6,0x48FFDA,0x48FFFF
    ,0x6D0000,0x6D0024,0x6D0048,0x6D006D
    ,0x6D0091,0x6D00B6,0x6D00DA,0x6D00FF
    ,0x6D5500,0x6D5524,0x6D5548,0x6D556D
    ,0x6D5591,0x6D55B6,0x6D55DA,0x6D55FF
    ,0x6DAA00,0x6DAA24,0x6DAA48,0x6DAA6D
    ,0x6DAA91,0x6DAAB6,0x6DAADA,0x6DAAFF
    ,0x6DFF00,0x6DFF24,0x6DFF48,0x6DFF6D
    ,0x6DFF91,0x6DFFB6,0x6DFFDA,0x6DFFFF
    ,0x910000,0x910024,0x910048,0x91006D
    ,0x910091,0x9100B6,0x9100DA,0x9100FF
    ,0x915500,0x915524,0x915548,0x91556D
    ,0x915591,0x9155B6,0x9155DA,0x9155FF
    ,0x91AA00,0x91AA24,0x91AA48,0x91AA6D
    ,0x91AA91,0x91AAB6,0x91AADA,0x91AAFF
    ,0x91FF00,0x91FF24,0x91FF48,0x91FF6D
    ,0x91FF91,0x91FFB6,0x91FFDA,0x91FFFF
    ,0xB60000,0xB60024,0xB60048,0xB6006D
    ,0xB60091,0xB600B6,0xB600DA,0xB600FF
    ,0xB65500,0xB65524,0xB65548,0xB6556D
    ,0xB65591,0xB655B6,0xB655DA,0xB655FF
    ,0xB6AA00,0xB6AA24,0xB6AA48,0xB6AA6D
    ,0xB6AA91,0xB6AAB6,0xB6AADA,0xB6AAFF
    ,0xB6FF00,0xB6FF24,0xB6FF48,0xB6FF6D
    ,0xB6FF91,0xB6FFB6,0xB6FFDA,0xB6FFFF
    ,0xDA0000,0xDA0024,0xDA0048,0xDA006D
    ,0xDA0091,0xDA00B6,0xDA00DA,0xDA00FF
    ,0xDA5500,0xDA5524,0xDA5548,0xDA556D
    ,0xDA5591,0xDA55B6,0xDA55DA,0xDA55FF
    ,0xDAAA00,0xDAAA24,0xDAAA48,0xDAAA6D
    ,0xDAAA91,0xDAAAB6,0xDAAADA,0xDAAAFF
    ,0xDAFF00,0xDAFF24,0xDAFF48,0xDAFF6D
    ,0xDAFF91,0xDAFFB6,0xDAFFDA,0xDAFFFF
    ,0xFF0000,0xFF0024,0xFF0048,0xFF006D
    ,0xFF0091,0xFF00B6,0xFF00DA,0xFF00FF
    ,0xFF5500,0xFF5524,0xFF5548,0xFF556D
    ,0xFF5591,0xFF55B6,0xFF55DA,0xFF55FF
    ,0xFFAA00,0xFFAA24,0xFFAA48,0xFFAA6D
    ,0xFFAA91,0xFFAAB6,0xFFAADA,0xFFAAFF
    ,0xFFFF00,0xFFFF24,0xFFFF48,0xFFFF6D
    ,0xFFFF91,0xFFFFB6,0xFFFFDA,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palbmp_speed127 = {
  256,	/* number of entries */
  0, 	/* No transparency */
  &Colorsbmp_speed127[0]
};

static GUI_CONST_STORAGE unsigned char acbmp_speed127[] = {
  /* RLE: 594 Pixels @ 000,000*/ 254, 0xE0, 254, 0xE0, 86, 0xE0, 
  /* ABS: 002 Pixels @ 034,007*/ 0, 2, 0xC0, 0xE0, 
  /* RLE: 008 Pixels @ 036,007*/ 8, 0xFF, 
  /* RLE: 069 Pixels @ 044,007*/ 69, 0xE0, 
  /* RLE: 014 Pixels @ 033,008*/ 14, 0xFF, 
  /* RLE: 064 Pixels @ 047,008*/ 64, 0xE0, 
  /* RLE: 018 Pixels @ 031,009*/ 18, 0xFF, 
  /* RLE: 061 Pixels @ 049,009*/ 61, 0xE0, 
  /* RLE: 020 Pixels @ 030,010*/ 20, 0xFF, 
  /* RLE: 059 Pixels @ 050,010*/ 59, 0xE0, 
  /* RLE: 008 Pixels @ 029,011*/ 8, 0xFF, 
  /* RLE: 006 Pixels @ 037,011*/ 6, 0xE0, 
  /* RLE: 009 Pixels @ 043,011*/ 9, 0xFF, 
  /* RLE: 001 Pixels @ 052,011*/ 1, 0xC0, 
  /* RLE: 054 Pixels @ 053,011*/ 54, 0xE0, 
  /* RLE: 007 Pixels @ 027,012*/ 7, 0xFF, 
  /* RLE: 010 Pixels @ 034,012*/ 10, 0xE0, 
  /* ABS: 002 Pixels @ 044,012*/ 0, 2, 0xC0, 0xE0, 
  /* RLE: 007 Pixels @ 046,012*/ 7, 0xFF, 
  /* RLE: 001 Pixels @ 053,012*/ 1, 0xC0, 
  /* RLE: 053 Pixels @ 054,012*/ 53, 0xE0, 
  /* RLE: 005 Pixels @ 027,013*/ 5, 0xFF, 
  /* ABS: 002 Pixels @ 032,013*/ 0, 2, 0xE0, 0xC0, 
  /* RLE: 014 Pixels @ 034,013*/ 14, 0xE0, 
  /* RLE: 006 Pixels @ 048,013*/ 6, 0xFF, 
  /* RLE: 001 Pixels @ 054,013*/ 1, 0xC0, 
  /* RLE: 051 Pixels @ 055,013*/ 51, 0xE0, 
  /* RLE: 005 Pixels @ 026,014*/ 5, 0xFF, 
  /* RLE: 017 Pixels @ 031,014*/ 17, 0xE0, 
  /* RLE: 001 Pixels @ 048,014*/ 1, 0xA0, 
  /* RLE: 006 Pixels @ 049,014*/ 6, 0xFF, 
  /* RLE: 050 Pixels @ 055,014*/ 50, 0xE0, 
  /* RLE: 005 Pixels @ 025,015*/ 5, 0xFF, 
  /* RLE: 019 Pixels @ 030,015*/ 19, 0xE0, 
  /* RLE: 001 Pixels @ 049,015*/ 1, 0xC0, 
  /* RLE: 005 Pixels @ 050,015*/ 5, 0xFF, 
  /* RLE: 049 Pixels @ 055,015*/ 49, 0xE0, 
  /* RLE: 005 Pixels @ 024,016*/ 5, 0xFF, 
  /* RLE: 022 Pixels @ 029,016*/ 22, 0xE0, 
  /* RLE: 005 Pixels @ 051,016*/ 5, 0xFF, 
  /* RLE: 001 Pixels @ 056,016*/ 1, 0xC0, 
  /* RLE: 047 Pixels @ 057,016*/ 47, 0xE0, 
  /* RLE: 004 Pixels @ 024,017*/ 4, 0xFF, 
  /* RLE: 024 Pixels @ 028,017*/ 24, 0xE0, 
  /* RLE: 004 Pixels @ 052,017*/ 4, 0xFF, 
  /* RLE: 048 Pixels @ 056,017*/ 48, 0xE0, 
  /* RLE: 004 Pixels @ 024,018*/ 4, 0xFF, 
  /* RLE: 024 Pixels @ 028,018*/ 24, 0xE0, 
  /* RLE: 005 Pixels @ 052,018*/ 5, 0xFF, 
  /* RLE: 045 Pixels @ 057,018*/ 45, 0xE0, 
  /* RLE: 001 Pixels @ 022,019*/ 1, 0xC0, 
  /* RLE: 004 Pixels @ 023,019*/ 4, 0xFF, 
  /* RLE: 026 Pixels @ 027,019*/ 26, 0xE0, 
  /* RLE: 004 Pixels @ 053,019*/ 4, 0xFF, 
  /* RLE: 046 Pixels @ 057,019*/ 46, 0xE0, 
  /* RLE: 004 Pixels @ 023,020*/ 4, 0xFF, 
  /* RLE: 026 Pixels @ 027,020*/ 26, 0xE0, 
  /* RLE: 004 Pixels @ 053,020*/ 4, 0xFF, 
  /* RLE: 045 Pixels @ 057,020*/ 45, 0xE0, 
  /* RLE: 005 Pixels @ 022,021*/ 5, 0xFF, 
  /* RLE: 006 Pixels @ 027,021*/ 6, 0xE0, 
  /* RLE: 001 Pixels @ 033,021*/ 1, 0xFF, 
  /* RLE: 004 Pixels @ 034,021*/ 4, 0xE0, 
  /* ABS: 008 Pixels @ 038,021*/ 0, 8, 0xFF, 0xFF, 0xE0, 0xE0, 0xE0, 0xFF, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 046,021*/ 8, 0xE0, 
  /* RLE: 004 Pixels @ 054,021*/ 4, 0xFF, 
  /* RLE: 044 Pixels @ 058,021*/ 44, 0xE0, 
  /* RLE: 004 Pixels @ 022,022*/ 4, 0xFF, 
  /* RLE: 006 Pixels @ 026,022*/ 6, 0xE0, 
  /* ABS: 010 Pixels @ 032,022*/ 0, 10, 0xFF, 0xFF, 0xE0, 0xE0, 0xE0, 0xFF, 0xE0, 0xE0, 0xFF, 0xE0, 
  /* RLE: 004 Pixels @ 042,022*/ 4, 0xFF, 
  /* RLE: 008 Pixels @ 046,022*/ 8, 0xE0, 
  /* RLE: 004 Pixels @ 054,022*/ 4, 0xFF, 
  /* RLE: 044 Pixels @ 058,022*/ 44, 0xE0, 
  /* RLE: 004 Pixels @ 022,023*/ 4, 0xFF, 
  /* RLE: 007 Pixels @ 026,023*/ 7, 0xE0, 
  /* ABS: 013 Pixels @ 033,023*/ 0, 13, 0xFF, 0xE0, 0xE0, 0xE0, 0xFF, 0xE0, 0xE0, 0xFF, 0xE0, 0xFF, 0xE0, 0xE0, 0xFF, 
  /* RLE: 008 Pixels @ 046,023*/ 8, 0xE0, 
  /* RLE: 004 Pixels @ 054,023*/ 4, 0xFF, 
  /* RLE: 044 Pixels @ 058,023*/ 44, 0xE0, 
  /* RLE: 004 Pixels @ 022,024*/ 4, 0xFF, 
  /* RLE: 007 Pixels @ 026,024*/ 7, 0xE0, 
  /* RLE: 001 Pixels @ 033,024*/ 1, 0xFF, 
  /* RLE: 006 Pixels @ 034,024*/ 6, 0xE0, 
  /* ABS: 006 Pixels @ 040,024*/ 0, 6, 0xFF, 0xE0, 0xE0, 0xE0, 0xE1, 0xFF, 
  /* RLE: 008 Pixels @ 046,024*/ 8, 0xE0, 
  /* RLE: 004 Pixels @ 054,024*/ 4, 0xFF, 
  /* RLE: 044 Pixels @ 058,024*/ 44, 0xE0, 
  /* RLE: 004 Pixels @ 022,025*/ 4, 0xFF, 
  /* RLE: 007 Pixels @ 026,025*/ 7, 0xE0, 
  /* RLE: 001 Pixels @ 033,025*/ 1, 0xFF, 
  /* RLE: 005 Pixels @ 034,025*/ 5, 0xE0, 
  /* RLE: 001 Pixels @ 039,025*/ 1, 0xFF, 
  /* RLE: 004 Pixels @ 040,025*/ 4, 0xE0, 
  /* RLE: 001 Pixels @ 044,025*/ 1, 0xFF, 
  /* RLE: 009 Pixels @ 045,025*/ 9, 0xE0, 
  /* RLE: 004 Pixels @ 054,025*/ 4, 0xFF, 
  /* RLE: 044 Pixels @ 058,025*/ 44, 0xE0, 
  /* RLE: 004 Pixels @ 022,026*/ 4, 0xFF, 
  /* RLE: 007 Pixels @ 026,026*/ 7, 0xE0, 
  /* RLE: 001 Pixels @ 033,026*/ 1, 0xFF, 
  /* RLE: 004 Pixels @ 034,026*/ 4, 0xE0, 
  /* RLE: 001 Pixels @ 038,026*/ 1, 0xFF, 
  /* RLE: 005 Pixels @ 039,026*/ 5, 0xE0, 
  /* RLE: 001 Pixels @ 044,026*/ 1, 0xFF, 
  /* RLE: 009 Pixels @ 045,026*/ 9, 0xE0, 
  /* RLE: 004 Pixels @ 054,026*/ 4, 0xFF, 
  /* RLE: 044 Pixels @ 058,026*/ 44, 0xE0, 
  /* RLE: 004 Pixels @ 022,027*/ 4, 0xFF, 
  /* RLE: 007 Pixels @ 026,027*/ 7, 0xE0, 
  /* ABS: 012 Pixels @ 033,027*/ 0, 12, 0xFF, 0xE0, 0xE0, 0xE0, 0xFF, 0xE0, 0xE0, 0xFF, 0xE0, 0xE0, 0xE0, 0xFF, 
  /* RLE: 009 Pixels @ 045,027*/ 9, 0xE0, 
  /* RLE: 004 Pixels @ 054,027*/ 4, 0xFF, 
  /* RLE: 044 Pixels @ 058,027*/ 44, 0xE0, 
  /* RLE: 005 Pixels @ 022,028*/ 5, 0xFF, 
  /* RLE: 005 Pixels @ 027,028*/ 5, 0xE0, 
  /* RLE: 003 Pixels @ 032,028*/ 3, 0xFF, 
  /* ABS: 002 Pixels @ 035,028*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 004 Pixels @ 037,028*/ 4, 0xFF, 
  /* RLE: 003 Pixels @ 041,028*/ 3, 0xE0, 
  /* RLE: 001 Pixels @ 044,028*/ 1, 0xFF, 
  /* RLE: 009 Pixels @ 045,028*/ 9, 0xE0, 
  /* RLE: 004 Pixels @ 054,028*/ 4, 0xFF, 
  /* RLE: 045 Pixels @ 058,028*/ 45, 0xE0, 
  /* RLE: 004 Pixels @ 023,029*/ 4, 0xFF, 
  /* RLE: 001 Pixels @ 027,029*/ 1, 0xC0, 
  /* RLE: 025 Pixels @ 028,029*/ 25, 0xE0, 
  /* RLE: 005 Pixels @ 053,029*/ 5, 0xFF, 
  /* RLE: 045 Pixels @ 058,029*/ 45, 0xE0, 
  /* RLE: 004 Pixels @ 023,030*/ 4, 0xFF, 
  /* RLE: 026 Pixels @ 027,030*/ 26, 0xE0, 
  /* RLE: 004 Pixels @ 053,030*/ 4, 0xFF, 
  /* RLE: 047 Pixels @ 057,030*/ 47, 0xE0, 
  /* RLE: 004 Pixels @ 024,031*/ 4, 0xFF, 
  /* RLE: 025 Pixels @ 028,031*/ 25, 0xE0, 
  /* RLE: 004 Pixels @ 053,031*/ 4, 0xFF, 
  /* RLE: 047 Pixels @ 057,031*/ 47, 0xE0, 
  /* RLE: 004 Pixels @ 024,032*/ 4, 0xFF, 
  /* RLE: 023 Pixels @ 028,032*/ 23, 0xE0, 
  /* RLE: 001 Pixels @ 051,032*/ 1, 0xA0, 
  /* RLE: 004 Pixels @ 052,032*/ 4, 0xFF, 
  /* RLE: 048 Pixels @ 056,032*/ 48, 0xE0, 
  /* RLE: 005 Pixels @ 024,033*/ 5, 0xFF, 
  /* RLE: 022 Pixels @ 029,033*/ 22, 0xE0, 
  /* RLE: 005 Pixels @ 051,033*/ 5, 0xFF, 
  /* RLE: 049 Pixels @ 056,033*/ 49, 0xE0, 
  /* RLE: 005 Pixels @ 025,034*/ 5, 0xFF, 
  /* RLE: 019 Pixels @ 030,034*/ 19, 0xE0, 
  /* RLE: 001 Pixels @ 049,034*/ 1, 0xC0, 
  /* RLE: 005 Pixels @ 050,034*/ 5, 0xFF, 
  /* RLE: 051 Pixels @ 055,034*/ 51, 0xE0, 
  /* RLE: 005 Pixels @ 026,035*/ 5, 0xFF, 
  /* RLE: 018 Pixels @ 031,035*/ 18, 0xE0, 
  /* RLE: 006 Pixels @ 049,035*/ 6, 0xFF, 
  /* RLE: 051 Pixels @ 055,035*/ 51, 0xE0, 
  /* RLE: 006 Pixels @ 026,036*/ 6, 0xFF, 
  /* RLE: 016 Pixels @ 032,036*/ 16, 0xE0, 
  /* RLE: 006 Pixels @ 048,036*/ 6, 0xFF, 
  /* RLE: 052 Pixels @ 054,036*/ 52, 0xE0, 
  /* RLE: 001 Pixels @ 026,037*/ 1, 0xC0, 
  /* RLE: 007 Pixels @ 027,037*/ 7, 0xFF, 
  /* RLE: 013 Pixels @ 034,037*/ 13, 0xE0, 
  /* RLE: 006 Pixels @ 047,037*/ 6, 0xFF, 
  /* RLE: 054 Pixels @ 053,037*/ 54, 0xE0, 
  /* RLE: 001 Pixels @ 027,038*/ 1, 0xC0, 
  /* RLE: 008 Pixels @ 028,038*/ 8, 0xFF, 
  /* RLE: 008 Pixels @ 036,038*/ 8, 0xE0, 
  /* RLE: 008 Pixels @ 044,038*/ 8, 0xFF, 
  /* RLE: 056 Pixels @ 052,038*/ 56, 0xE0, 
  /* ABS: 002 Pixels @ 028,039*/ 0, 2, 0xC0, 0xE0, 
  /* RLE: 021 Pixels @ 030,039*/ 21, 0xFF, 
  /* RLE: 060 Pixels @ 051,039*/ 60, 0xE0, 
  /* RLE: 018 Pixels @ 031,040*/ 18, 0xFF, 
  /* RLE: 062 Pixels @ 049,040*/ 62, 0xE0, 
  /* ABS: 002 Pixels @ 031,041*/ 0, 2, 0xC0, 0xE0, 
  /* RLE: 014 Pixels @ 033,041*/ 14, 0xFF, 
  /* RLE: 069 Pixels @ 047,041*/ 69, 0xE0, 
  /* RLE: 008 Pixels @ 036,042*/ 8, 0xFF, 
  /* RLE: 596 Pixels @ 044,042*/ 254, 0xE0, 254, 0xE0, 88, 0xE0, 


  0};  /* 427 for 4000 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmbmp_speed127 = {
  80, /* XSize */
  50, /* YSize */
  80, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acbmp_speed127,  /* Pointer to picture data (indices) */
  &Palbmp_speed127  /* Pointer to palette */
 ,GUI_DRAW_RLE8
};

/* *** End of file *** */
