/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: bmp_baud115200_sel
* Dimensions:  80 * 50
* NumColors:   256
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsbmp_baud115200_sel[] = {
     0x000000,0x000024,0x000048,0x00006D
    ,0x000091,0x0000B6,0x0000DA,0x0000FF
    ,0x005500,0x005524,0x005548,0x00556D
    ,0x005591,0x0055B6,0x0055DA,0x0055FF
    ,0x00AA00,0x00AA24,0x00AA48,0x00AA6D
    ,0x00AA91,0x00AAB6,0x00AADA,0x00AAFF
    ,0x00FF00,0x00FF24,0x00FF48,0x00FF6D
    ,0x00FF91,0x00FFB6,0x00FFDA,0x00FFFF
    ,0x240000,0x240024,0x240048,0x24006D
    ,0x240091,0x2400B6,0x2400DA,0x2400FF
    ,0x245500,0x245524,0x245548,0x24556D
    ,0x245591,0x2455B6,0x2455DA,0x2455FF
    ,0x24AA00,0x24AA24,0x24AA48,0x24AA6D
    ,0x24AA91,0x24AAB6,0x24AADA,0x24AAFF
    ,0x24FF00,0x24FF24,0x24FF48,0x24FF6D
    ,0x24FF91,0x24FFB6,0x24FFDA,0x24FFFF
    ,0x480000,0x480024,0x480048,0x48006D
    ,0x480091,0x4800B6,0x4800DA,0x4800FF
    ,0x485500,0x485524,0x485548,0x48556D
    ,0x485591,0x4855B6,0x4855DA,0x4855FF
    ,0x48AA00,0x48AA24,0x48AA48,0x48AA6D
    ,0x48AA91,0x48AAB6,0x48AADA,0x48AAFF
    ,0x48FF00,0x48FF24,0x48FF48,0x48FF6D
    ,0x48FF91,0x48FFB6,0x48FFDA,0x48FFFF
    ,0x6D0000,0x6D0024,0x6D0048,0x6D006D
    ,0x6D0091,0x6D00B6,0x6D00DA,0x6D00FF
    ,0x6D5500,0x6D5524,0x6D5548,0x6D556D
    ,0x6D5591,0x6D55B6,0x6D55DA,0x6D55FF
    ,0x6DAA00,0x6DAA24,0x6DAA48,0x6DAA6D
    ,0x6DAA91,0x6DAAB6,0x6DAADA,0x6DAAFF
    ,0x6DFF00,0x6DFF24,0x6DFF48,0x6DFF6D
    ,0x6DFF91,0x6DFFB6,0x6DFFDA,0x6DFFFF
    ,0x910000,0x910024,0x910048,0x91006D
    ,0x910091,0x9100B6,0x9100DA,0x9100FF
    ,0x915500,0x915524,0x915548,0x91556D
    ,0x915591,0x9155B6,0x9155DA,0x9155FF
    ,0x91AA00,0x91AA24,0x91AA48,0x91AA6D
    ,0x91AA91,0x91AAB6,0x91AADA,0x91AAFF
    ,0x91FF00,0x91FF24,0x91FF48,0x91FF6D
    ,0x91FF91,0x91FFB6,0x91FFDA,0x91FFFF
    ,0xB60000,0xB60024,0xB60048,0xB6006D
    ,0xB60091,0xB600B6,0xB600DA,0xB600FF
    ,0xB65500,0xB65524,0xB65548,0xB6556D
    ,0xB65591,0xB655B6,0xB655DA,0xB655FF
    ,0xB6AA00,0xB6AA24,0xB6AA48,0xB6AA6D
    ,0xB6AA91,0xB6AAB6,0xB6AADA,0xB6AAFF
    ,0xB6FF00,0xB6FF24,0xB6FF48,0xB6FF6D
    ,0xB6FF91,0xB6FFB6,0xB6FFDA,0xB6FFFF
    ,0xDA0000,0xDA0024,0xDA0048,0xDA006D
    ,0xDA0091,0xDA00B6,0xDA00DA,0xDA00FF
    ,0xDA5500,0xDA5524,0xDA5548,0xDA556D
    ,0xDA5591,0xDA55B6,0xDA55DA,0xDA55FF
    ,0xDAAA00,0xDAAA24,0xDAAA48,0xDAAA6D
    ,0xDAAA91,0xDAAAB6,0xDAAADA,0xDAAAFF
    ,0xDAFF00,0xDAFF24,0xDAFF48,0xDAFF6D
    ,0xDAFF91,0xDAFFB6,0xDAFFDA,0xDAFFFF
    ,0xFF0000,0xFF0024,0xFF0048,0xFF006D
    ,0xFF0091,0xFF00B6,0xFF00DA,0xFF00FF
    ,0xFF5500,0xFF5524,0xFF5548,0xFF556D
    ,0xFF5591,0xFF55B6,0xFF55DA,0xFF55FF
    ,0xFFAA00,0xFFAA24,0xFFAA48,0xFFAA6D
    ,0xFFAA91,0xFFAAB6,0xFFAADA,0xFFAAFF
    ,0xFFFF00,0xFFFF24,0xFFFF48,0xFFFF6D
    ,0xFFFF91,0xFFFFB6,0xFFFFDA,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palbmp_baud115200_sel = {
  256,	/* number of entries */
  0, 	/* No transparency */
  &Colorsbmp_baud115200_sel[0]
};

static GUI_CONST_STORAGE unsigned char acbmp_baud115200_sel[] = {
  /* RLE: 755 Pixels @ 000,000*/ 254, 0x10, 254, 0x10, 247, 0x10, 
  /* RLE: 011 Pixels @ 035,009*/ 11, 0xFF, 
  /* RLE: 065 Pixels @ 046,009*/ 65, 0x10, 
  /* RLE: 018 Pixels @ 031,010*/ 18, 0xFF, 
  /* RLE: 060 Pixels @ 049,010*/ 60, 0x10, 
  /* RLE: 022 Pixels @ 029,011*/ 22, 0xFF, 
  /* RLE: 057 Pixels @ 051,011*/ 57, 0x10, 
  /* RLE: 007 Pixels @ 028,012*/ 7, 0xFF, 
  /* RLE: 010 Pixels @ 035,012*/ 10, 0x10, 
  /* RLE: 008 Pixels @ 045,012*/ 8, 0xFF, 
  /* RLE: 053 Pixels @ 053,012*/ 53, 0x10, 
  /* RLE: 006 Pixels @ 026,013*/ 6, 0xFF, 
  /* RLE: 016 Pixels @ 032,013*/ 16, 0x10, 
  /* RLE: 007 Pixels @ 048,013*/ 7, 0xFF, 
  /* RLE: 049 Pixels @ 055,013*/ 49, 0x10, 
  /* RLE: 006 Pixels @ 024,014*/ 6, 0xFF, 
  /* RLE: 020 Pixels @ 030,014*/ 20, 0x10, 
  /* RLE: 006 Pixels @ 050,014*/ 6, 0xFF, 
  /* RLE: 047 Pixels @ 056,014*/ 47, 0x10, 
  /* RLE: 005 Pixels @ 023,015*/ 5, 0xFF, 
  /* RLE: 024 Pixels @ 028,015*/ 24, 0x10, 
  /* RLE: 005 Pixels @ 052,015*/ 5, 0xFF, 
  /* RLE: 046 Pixels @ 057,015*/ 46, 0x10, 
  /* RLE: 004 Pixels @ 023,016*/ 4, 0xFF, 
  /* RLE: 026 Pixels @ 027,016*/ 26, 0x10, 
  /* RLE: 005 Pixels @ 053,016*/ 5, 0xFF, 
  /* RLE: 044 Pixels @ 058,016*/ 44, 0x10, 
  /* RLE: 003 Pixels @ 022,017*/ 3, 0xFF, 
  /* RLE: 029 Pixels @ 025,017*/ 29, 0x10, 
  /* RLE: 004 Pixels @ 054,017*/ 4, 0xFF, 
  /* RLE: 043 Pixels @ 058,017*/ 43, 0x10, 
  /* RLE: 004 Pixels @ 021,018*/ 4, 0xFF, 
  /* RLE: 030 Pixels @ 025,018*/ 30, 0x10, 
  /* RLE: 004 Pixels @ 055,018*/ 4, 0xFF, 
  /* RLE: 042 Pixels @ 059,018*/ 42, 0x10, 
  /* RLE: 003 Pixels @ 021,019*/ 3, 0xFF, 
  /* RLE: 032 Pixels @ 024,019*/ 32, 0x10, 
  /* RLE: 003 Pixels @ 056,019*/ 3, 0xFF, 
  /* RLE: 041 Pixels @ 059,019*/ 41, 0x10, 
  /* RLE: 003 Pixels @ 020,020*/ 3, 0xFF, 
  /* ABS: 003 Pixels @ 023,020*/ 0, 3, 0x10, 0x10, 0xFF, 
  /* RLE: 005 Pixels @ 026,020*/ 5, 0x10, 
  /* ABS: 003 Pixels @ 031,020*/ 0, 3, 0xFF, 0x10, 0x10, 
  /* RLE: 005 Pixels @ 034,020*/ 5, 0xFF, 
  /* RLE: 003 Pixels @ 039,020*/ 3, 0x10, 
  /* ABS: 017 Pixels @ 042,020*/ 0, 17, 0xFF, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0xFF, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0xFF, 0xFF, 0x10, 0xFF, 0xFF, 
  /* RLE: 041 Pixels @ 059,020*/ 41, 0x10, 
  /* RLE: 003 Pixels @ 020,021*/ 3, 0xFF, 
  /* ABS: 003 Pixels @ 023,021*/ 0, 3, 0x10, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 026,021*/ 4, 0x10, 
  /* ABS: 005 Pixels @ 030,021*/ 0, 5, 0xFF, 0xFF, 0x10, 0x10, 0xFF, 
  /* RLE: 006 Pixels @ 035,021*/ 6, 0x10, 
  /* ABS: 014 Pixels @ 041,021*/ 0, 14, 0xFF, 0x10, 0x10, 0xFF, 0x10, 0xFF, 0xFF, 0x10, 0xFF, 0xFF, 0x10, 0xFF, 0xFF, 0x10, 
  /* RLE: 005 Pixels @ 055,021*/ 5, 0xFF, 
  /* RLE: 039 Pixels @ 060,021*/ 39, 0x10, 
  /* RLE: 003 Pixels @ 019,022*/ 3, 0xFF, 
  /* ABS: 013 Pixels @ 022,022*/ 0, 13, 0x10, 0xFF, 0xFF, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0xFF, 0xFF, 0x10, 0x10, 0xFF, 
  /* RLE: 005 Pixels @ 035,022*/ 5, 0x10, 
  /* ABS: 021 Pixels @ 040,022*/ 0, 21, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0x10, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0x10, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0x10, 0xFF, 0xFF, 0xFF, 
  /* RLE: 038 Pixels @ 061,022*/ 38, 0x10, 
  /* RLE: 003 Pixels @ 019,023*/ 3, 0xFF, 
  /* RLE: 003 Pixels @ 022,023*/ 3, 0x10, 
  /* RLE: 001 Pixels @ 025,023*/ 1, 0xFF, 
  /* RLE: 005 Pixels @ 026,023*/ 5, 0x10, 
  /* ABS: 003 Pixels @ 031,023*/ 0, 3, 0xFF, 0x10, 0x10, 
  /* RLE: 005 Pixels @ 034,023*/ 5, 0xFF, 
  /* RLE: 005 Pixels @ 039,023*/ 5, 0x10, 
  /* ABS: 017 Pixels @ 044,023*/ 0, 17, 0xFF, 0x10, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0x10, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0x10, 0xFF, 0xFF, 0xFF, 
  /* RLE: 038 Pixels @ 061,023*/ 38, 0x10, 
  /* RLE: 003 Pixels @ 019,024*/ 3, 0xFF, 
  /* RLE: 003 Pixels @ 022,024*/ 3, 0x10, 
  /* RLE: 001 Pixels @ 025,024*/ 1, 0xFF, 
  /* RLE: 005 Pixels @ 026,024*/ 5, 0x10, 
  /* RLE: 001 Pixels @ 031,024*/ 1, 0xFF, 
  /* RLE: 006 Pixels @ 032,024*/ 6, 0x10, 
  /* RLE: 001 Pixels @ 038,024*/ 1, 0xFF, 
  /* RLE: 004 Pixels @ 039,024*/ 4, 0x10, 
  /* ABS: 018 Pixels @ 043,024*/ 0, 18, 0xFF, 0x10, 0x10, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0x10, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0x10, 0xFF, 0xFF, 0xFF, 
  /* RLE: 038 Pixels @ 061,024*/ 38, 0x10, 
  /* RLE: 003 Pixels @ 019,025*/ 3, 0xFF, 
  /* RLE: 003 Pixels @ 022,025*/ 3, 0x10, 
  /* RLE: 001 Pixels @ 025,025*/ 1, 0xFF, 
  /* RLE: 005 Pixels @ 026,025*/ 5, 0x10, 
  /* RLE: 001 Pixels @ 031,025*/ 1, 0xFF, 
  /* RLE: 006 Pixels @ 032,025*/ 6, 0x10, 
  /* ABS: 023 Pixels @ 038,025*/ 0, 23, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0x10, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0x10, 0xFF, 0xFF, 0xFF, 
  /* RLE: 038 Pixels @ 061,025*/ 38, 0x10, 
  /* RLE: 003 Pixels @ 019,026*/ 3, 0xFF, 
  /* RLE: 003 Pixels @ 022,026*/ 3, 0x10, 
  /* RLE: 001 Pixels @ 025,026*/ 1, 0xFF, 
  /* RLE: 005 Pixels @ 026,026*/ 5, 0x10, 
  /* RLE: 001 Pixels @ 031,026*/ 1, 0xFF, 
  /* RLE: 006 Pixels @ 032,026*/ 6, 0x10, 
  /* ABS: 004 Pixels @ 038,026*/ 0, 4, 0xFF, 0x10, 0x10, 0xFF, 
  /* RLE: 004 Pixels @ 042,026*/ 4, 0x10, 
  /* ABS: 015 Pixels @ 046,026*/ 0, 15, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0x10, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0x10, 0xFF, 0xFF, 0xFF, 
  /* RLE: 038 Pixels @ 061,026*/ 38, 0x10, 
  /* RLE: 003 Pixels @ 019,027*/ 3, 0xFF, 
  /* RLE: 003 Pixels @ 022,027*/ 3, 0x10, 
  /* RLE: 001 Pixels @ 025,027*/ 1, 0xFF, 
  /* RLE: 005 Pixels @ 026,027*/ 5, 0x10, 
  /* RLE: 001 Pixels @ 031,027*/ 1, 0xFF, 
  /* RLE: 006 Pixels @ 032,027*/ 6, 0x10, 
  /* ABS: 003 Pixels @ 038,027*/ 0, 3, 0xFF, 0x10, 0xFF, 
  /* RLE: 005 Pixels @ 041,027*/ 5, 0x10, 
  /* ABS: 015 Pixels @ 046,027*/ 0, 15, 0xFF, 0xFF, 0x10, 0xFF, 0xFF, 0x10, 0xFF, 0xFF, 0x10, 0xFF, 0xFF, 0x10, 0xFF, 0xFF, 0xFF, 
  /* RLE: 039 Pixels @ 061,027*/ 39, 0x10, 
  /* RLE: 003 Pixels @ 020,028*/ 3, 0xFF, 
  /* ABS: 003 Pixels @ 023,028*/ 0, 3, 0x10, 0x10, 0xFF, 
  /* RLE: 005 Pixels @ 026,028*/ 5, 0x10, 
  /* ABS: 003 Pixels @ 031,028*/ 0, 3, 0xFF, 0x10, 0x10, 
  /* RLE: 005 Pixels @ 034,028*/ 5, 0xFF, 
  /* RLE: 001 Pixels @ 039,028*/ 1, 0x10, 
  /* RLE: 005 Pixels @ 040,028*/ 5, 0xFF, 
  /* ABS: 012 Pixels @ 045,028*/ 0, 12, 0x10, 0x10, 0xFF, 0xFF, 0xFF, 0x10, 0x10, 0x10, 0xFF, 0xFF, 0xFF, 0x10, 
  /* RLE: 004 Pixels @ 057,028*/ 4, 0xFF, 
  /* RLE: 039 Pixels @ 061,028*/ 39, 0x10, 
  /* RLE: 003 Pixels @ 020,029*/ 3, 0xFF, 
  /* RLE: 034 Pixels @ 023,029*/ 34, 0x10, 
  /* RLE: 003 Pixels @ 057,029*/ 3, 0xFF, 
  /* RLE: 041 Pixels @ 060,029*/ 41, 0x10, 
  /* RLE: 003 Pixels @ 021,030*/ 3, 0xFF, 
  /* RLE: 032 Pixels @ 024,030*/ 32, 0x10, 
  /* RLE: 004 Pixels @ 056,030*/ 4, 0xFF, 
  /* RLE: 041 Pixels @ 060,030*/ 41, 0x10, 
  /* RLE: 003 Pixels @ 021,031*/ 3, 0xFF, 
  /* RLE: 032 Pixels @ 024,031*/ 32, 0x10, 
  /* RLE: 003 Pixels @ 056,031*/ 3, 0xFF, 
  /* RLE: 043 Pixels @ 059,031*/ 43, 0x10, 
  /* RLE: 003 Pixels @ 022,032*/ 3, 0xFF, 
  /* RLE: 030 Pixels @ 025,032*/ 30, 0x10, 
  /* RLE: 003 Pixels @ 055,032*/ 3, 0xFF, 
  /* RLE: 044 Pixels @ 058,032*/ 44, 0x10, 
  /* RLE: 004 Pixels @ 022,033*/ 4, 0xFF, 
  /* RLE: 028 Pixels @ 026,033*/ 28, 0x10, 
  /* RLE: 004 Pixels @ 054,033*/ 4, 0xFF, 
  /* RLE: 045 Pixels @ 058,033*/ 45, 0x10, 
  /* RLE: 005 Pixels @ 023,034*/ 5, 0xFF, 
  /* RLE: 025 Pixels @ 028,034*/ 25, 0x10, 
  /* RLE: 004 Pixels @ 053,034*/ 4, 0xFF, 
  /* RLE: 047 Pixels @ 057,034*/ 47, 0x10, 
  /* RLE: 005 Pixels @ 024,035*/ 5, 0xFF, 
  /* RLE: 022 Pixels @ 029,035*/ 22, 0x10, 
  /* RLE: 005 Pixels @ 051,035*/ 5, 0xFF, 
  /* RLE: 049 Pixels @ 056,035*/ 49, 0x10, 
  /* RLE: 006 Pixels @ 025,036*/ 6, 0xFF, 
  /* RLE: 018 Pixels @ 031,036*/ 18, 0x10, 
  /* RLE: 005 Pixels @ 049,036*/ 5, 0xFF, 
  /* RLE: 053 Pixels @ 054,036*/ 53, 0x10, 
  /* RLE: 007 Pixels @ 027,037*/ 7, 0xFF, 
  /* RLE: 011 Pixels @ 034,037*/ 11, 0x10, 
  /* RLE: 008 Pixels @ 045,037*/ 8, 0xFF, 
  /* RLE: 056 Pixels @ 053,037*/ 56, 0x10, 
  /* RLE: 022 Pixels @ 029,038*/ 22, 0xFF, 
  /* RLE: 060 Pixels @ 051,038*/ 60, 0x10, 
  /* RLE: 018 Pixels @ 031,039*/ 18, 0xFF, 
  /* RLE: 066 Pixels @ 049,039*/ 66, 0x10, 
  /* RLE: 010 Pixels @ 035,040*/ 10, 0xFF, 
  /* RLE: 755 Pixels @ 045,040*/ 254, 0x10, 254, 0x10, 247, 0x10, 


  0};  /* 521 for 4000 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmbmp_baud115200_sel = {
  80, /* XSize */
  50, /* YSize */
  80, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acbmp_baud115200_sel,  /* Pointer to picture data (indices) */
  &Palbmp_baud115200_sel  /* Pointer to palette */
 ,GUI_DRAW_RLE8
};

/* *** End of file *** */
