/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: bmp_extru
* Dimensions:  80 * 50
* NumColors:   256
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsbmp_extru[] = {
     0x000000,0x000024,0x000048,0x00006D
    ,0x000091,0x0000B6,0x0000DA,0x0000FF
    ,0x005500,0x005524,0x005548,0x00556D
    ,0x005591,0x0055B6,0x0055DA,0x0055FF
    ,0x00AA00,0x00AA24,0x00AA48,0x00AA6D
    ,0x00AA91,0x00AAB6,0x00AADA,0x00AAFF
    ,0x00FF00,0x00FF24,0x00FF48,0x00FF6D
    ,0x00FF91,0x00FFB6,0x00FFDA,0x00FFFF
    ,0x240000,0x240024,0x240048,0x24006D
    ,0x240091,0x2400B6,0x2400DA,0x2400FF
    ,0x245500,0x245524,0x245548,0x24556D
    ,0x245591,0x2455B6,0x2455DA,0x2455FF
    ,0x24AA00,0x24AA24,0x24AA48,0x24AA6D
    ,0x24AA91,0x24AAB6,0x24AADA,0x24AAFF
    ,0x24FF00,0x24FF24,0x24FF48,0x24FF6D
    ,0x24FF91,0x24FFB6,0x24FFDA,0x24FFFF
    ,0x480000,0x480024,0x480048,0x48006D
    ,0x480091,0x4800B6,0x4800DA,0x4800FF
    ,0x485500,0x485524,0x485548,0x48556D
    ,0x485591,0x4855B6,0x4855DA,0x4855FF
    ,0x48AA00,0x48AA24,0x48AA48,0x48AA6D
    ,0x48AA91,0x48AAB6,0x48AADA,0x48AAFF
    ,0x48FF00,0x48FF24,0x48FF48,0x48FF6D
    ,0x48FF91,0x48FFB6,0x48FFDA,0x48FFFF
    ,0x6D0000,0x6D0024,0x6D0048,0x6D006D
    ,0x6D0091,0x6D00B6,0x6D00DA,0x6D00FF
    ,0x6D5500,0x6D5524,0x6D5548,0x6D556D
    ,0x6D5591,0x6D55B6,0x6D55DA,0x6D55FF
    ,0x6DAA00,0x6DAA24,0x6DAA48,0x6DAA6D
    ,0x6DAA91,0x6DAAB6,0x6DAADA,0x6DAAFF
    ,0x6DFF00,0x6DFF24,0x6DFF48,0x6DFF6D
    ,0x6DFF91,0x6DFFB6,0x6DFFDA,0x6DFFFF
    ,0x910000,0x910024,0x910048,0x91006D
    ,0x910091,0x9100B6,0x9100DA,0x9100FF
    ,0x915500,0x915524,0x915548,0x91556D
    ,0x915591,0x9155B6,0x9155DA,0x9155FF
    ,0x91AA00,0x91AA24,0x91AA48,0x91AA6D
    ,0x91AA91,0x91AAB6,0x91AADA,0x91AAFF
    ,0x91FF00,0x91FF24,0x91FF48,0x91FF6D
    ,0x91FF91,0x91FFB6,0x91FFDA,0x91FFFF
    ,0xB60000,0xB60024,0xB60048,0xB6006D
    ,0xB60091,0xB600B6,0xB600DA,0xB600FF
    ,0xB65500,0xB65524,0xB65548,0xB6556D
    ,0xB65591,0xB655B6,0xB655DA,0xB655FF
    ,0xB6AA00,0xB6AA24,0xB6AA48,0xB6AA6D
    ,0xB6AA91,0xB6AAB6,0xB6AADA,0xB6AAFF
    ,0xB6FF00,0xB6FF24,0xB6FF48,0xB6FF6D
    ,0xB6FF91,0xB6FFB6,0xB6FFDA,0xB6FFFF
    ,0xDA0000,0xDA0024,0xDA0048,0xDA006D
    ,0xDA0091,0xDA00B6,0xDA00DA,0xDA00FF
    ,0xDA5500,0xDA5524,0xDA5548,0xDA556D
    ,0xDA5591,0xDA55B6,0xDA55DA,0xDA55FF
    ,0xDAAA00,0xDAAA24,0xDAAA48,0xDAAA6D
    ,0xDAAA91,0xDAAAB6,0xDAAADA,0xDAAAFF
    ,0xDAFF00,0xDAFF24,0xDAFF48,0xDAFF6D
    ,0xDAFF91,0xDAFFB6,0xDAFFDA,0xDAFFFF
    ,0xFF0000,0xFF0024,0xFF0048,0xFF006D
    ,0xFF0091,0xFF00B6,0xFF00DA,0xFF00FF
    ,0xFF5500,0xFF5524,0xFF5548,0xFF556D
    ,0xFF5591,0xFF55B6,0xFF55DA,0xFF55FF
    ,0xFFAA00,0xFFAA24,0xFFAA48,0xFFAA6D
    ,0xFFAA91,0xFFAAB6,0xFFAADA,0xFFAAFF
    ,0xFFFF00,0xFFFF24,0xFFFF48,0xFFFF6D
    ,0xFFFF91,0xFFFFB6,0xFFFFDA,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palbmp_extru = {
  256,	/* number of entries */
  0, 	/* No transparency */
  &Colorsbmp_extru[0]
};

static GUI_CONST_STORAGE unsigned char acbmp_extru[] = {
  /* RLE: 355 Pixels @ 000,000*/ 254, 0xE0, 101, 0xE0, 
  /* ABS: 002 Pixels @ 035,004*/ 0, 2, 0xD7, 0xDF, 
  /* RLE: 004 Pixels @ 037,004*/ 4, 0xFF, 
  /* ABS: 002 Pixels @ 041,004*/ 0, 2, 0xDF, 0xD7, 
  /* RLE: 069 Pixels @ 043,004*/ 69, 0xE0, 
  /* RLE: 001 Pixels @ 032,005*/ 1, 0xB7, 
  /* RLE: 012 Pixels @ 033,005*/ 12, 0xFF, 
  /* RLE: 001 Pixels @ 045,005*/ 1, 0xB7, 
  /* RLE: 065 Pixels @ 046,005*/ 65, 0xE0, 
  /* ABS: 005 Pixels @ 031,006*/ 0, 5, 0xDF, 0xFF, 0xFF, 0xDF, 0xB7, 
  /* RLE: 006 Pixels @ 036,006*/ 6, 0xE0, 
  /* ABS: 005 Pixels @ 042,006*/ 0, 5, 0xB7, 0xDF, 0xFF, 0xFF, 0xDF, 
  /* RLE: 063 Pixels @ 047,006*/ 63, 0xE0, 
  /* ABS: 004 Pixels @ 030,007*/ 0, 4, 0xFF, 0xFF, 0xDF, 0xB7, 
  /* RLE: 010 Pixels @ 034,007*/ 10, 0xE0, 
  /* ABS: 004 Pixels @ 044,007*/ 0, 4, 0xB7, 0xDF, 0xFF, 0xFF, 
  /* RLE: 061 Pixels @ 048,007*/ 61, 0xE0, 
  /* ABS: 003 Pixels @ 029,008*/ 0, 3, 0xFF, 0xFF, 0xD7, 
  /* RLE: 014 Pixels @ 032,008*/ 14, 0xE0, 
  /* ABS: 003 Pixels @ 046,008*/ 0, 3, 0xD7, 0xFF, 0xFF, 
  /* RLE: 059 Pixels @ 049,008*/ 59, 0xE0, 
  /* ABS: 003 Pixels @ 028,009*/ 0, 3, 0xFF, 0xFF, 0xD7, 
  /* RLE: 016 Pixels @ 031,009*/ 16, 0xE0, 
  /* ABS: 003 Pixels @ 047,009*/ 0, 3, 0xD7, 0xFF, 0xFF, 
  /* RLE: 057 Pixels @ 050,009*/ 57, 0xE0, 
  /* ABS: 003 Pixels @ 027,010*/ 0, 3, 0xDF, 0xFF, 0xDF, 
  /* RLE: 018 Pixels @ 030,010*/ 18, 0xE0, 
  /* ABS: 003 Pixels @ 048,010*/ 0, 3, 0xDF, 0xFF, 0xDF, 
  /* RLE: 055 Pixels @ 051,010*/ 55, 0xE0, 
  /* ABS: 003 Pixels @ 026,011*/ 0, 3, 0xB7, 0xFF, 0xDF, 
  /* RLE: 020 Pixels @ 029,011*/ 20, 0xE0, 
  /* ABS: 003 Pixels @ 049,011*/ 0, 3, 0xDF, 0xFF, 0xB7, 
  /* RLE: 054 Pixels @ 052,011*/ 54, 0xE0, 
  /* ABS: 003 Pixels @ 026,012*/ 0, 3, 0xDF, 0xFF, 0xB7, 
  /* RLE: 020 Pixels @ 029,012*/ 20, 0xE0, 
  /* ABS: 003 Pixels @ 049,012*/ 0, 3, 0xB7, 0xFF, 0xDF, 
  /* RLE: 054 Pixels @ 052,012*/ 54, 0xE0, 
  /* ABS: 002 Pixels @ 026,013*/ 0, 2, 0xFF, 0xDF, 
  /* RLE: 008 Pixels @ 028,013*/ 8, 0xE0, 
  /* ABS: 006 Pixels @ 036,013*/ 0, 6, 0xB7, 0xDF, 0xFF, 0xFF, 0xDF, 0xB7, 
  /* RLE: 008 Pixels @ 042,013*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 050,013*/ 0, 2, 0xDF, 0xFF, 
  /* RLE: 053 Pixels @ 052,013*/ 53, 0xE0, 
  /* ABS: 003 Pixels @ 025,014*/ 0, 3, 0xB7, 0xFF, 0xD7, 
  /* RLE: 007 Pixels @ 028,014*/ 7, 0xE0, 
  /* RLE: 001 Pixels @ 035,014*/ 1, 0xB7, 
  /* RLE: 006 Pixels @ 036,014*/ 6, 0xFF, 
  /* RLE: 001 Pixels @ 042,014*/ 1, 0xB7, 
  /* RLE: 007 Pixels @ 043,014*/ 7, 0xE0, 
  /* ABS: 003 Pixels @ 050,014*/ 0, 3, 0xD7, 0xFF, 0xB7, 
  /* RLE: 052 Pixels @ 053,014*/ 52, 0xE0, 
  /* ABS: 002 Pixels @ 025,015*/ 0, 2, 0xDF, 0xFF, 
  /* RLE: 007 Pixels @ 027,015*/ 7, 0xE0, 
  /* ABS: 010 Pixels @ 034,015*/ 0, 10, 0xB7, 0xFF, 0xFF, 0xB7, 0xE0, 0xE0, 0xB7, 0xFF, 0xFF, 0xB7, 
  /* RLE: 007 Pixels @ 044,015*/ 7, 0xE0, 
  /* ABS: 002 Pixels @ 051,015*/ 0, 2, 0xFF, 0xDF, 
  /* RLE: 052 Pixels @ 053,015*/ 52, 0xE0, 
  /* ABS: 002 Pixels @ 025,016*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 027,016*/ 7, 0xE0, 
  /* ABS: 003 Pixels @ 034,016*/ 0, 3, 0xDF, 0xFF, 0xB7, 
  /* RLE: 004 Pixels @ 037,016*/ 4, 0xE0, 
  /* ABS: 003 Pixels @ 041,016*/ 0, 3, 0xB7, 0xFF, 0xDF, 
  /* RLE: 007 Pixels @ 044,016*/ 7, 0xE0, 
  /* ABS: 002 Pixels @ 051,016*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 052 Pixels @ 053,016*/ 52, 0xE0, 
  /* ABS: 002 Pixels @ 025,017*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 027,017*/ 7, 0xE0, 
  /* ABS: 002 Pixels @ 034,017*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 006 Pixels @ 036,017*/ 6, 0xE0, 
  /* ABS: 002 Pixels @ 042,017*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 044,017*/ 7, 0xE0, 
  /* ABS: 002 Pixels @ 051,017*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 052 Pixels @ 053,017*/ 52, 0xE0, 
  /* ABS: 002 Pixels @ 025,018*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 027,018*/ 7, 0xE0, 
  /* ABS: 002 Pixels @ 034,018*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 006 Pixels @ 036,018*/ 6, 0xE0, 
  /* ABS: 002 Pixels @ 042,018*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 044,018*/ 7, 0xE0, 
  /* ABS: 002 Pixels @ 051,018*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 052 Pixels @ 053,018*/ 52, 0xE0, 
  /* ABS: 002 Pixels @ 025,019*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 027,019*/ 7, 0xE0, 
  /* ABS: 003 Pixels @ 034,019*/ 0, 3, 0xDF, 0xFF, 0xB7, 
  /* RLE: 004 Pixels @ 037,019*/ 4, 0xE0, 
  /* ABS: 003 Pixels @ 041,019*/ 0, 3, 0xB7, 0xFF, 0xDF, 
  /* RLE: 007 Pixels @ 044,019*/ 7, 0xE0, 
  /* ABS: 002 Pixels @ 051,019*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 052 Pixels @ 053,019*/ 52, 0xE0, 
  /* ABS: 003 Pixels @ 025,020*/ 0, 3, 0xD7, 0xFF, 0xB7, 
  /* RLE: 006 Pixels @ 028,020*/ 6, 0xE0, 
  /* ABS: 010 Pixels @ 034,020*/ 0, 10, 0xB7, 0xFF, 0xFF, 0xB7, 0xE0, 0xE0, 0xB7, 0xFF, 0xFF, 0xB7, 
  /* RLE: 006 Pixels @ 044,020*/ 6, 0xE0, 
  /* ABS: 003 Pixels @ 050,020*/ 0, 3, 0xB7, 0xFF, 0xD7, 
  /* RLE: 052 Pixels @ 053,020*/ 52, 0xE0, 
  /* ABS: 003 Pixels @ 025,021*/ 0, 3, 0xB7, 0xFF, 0xDF, 
  /* RLE: 007 Pixels @ 028,021*/ 7, 0xE0, 
  /* RLE: 001 Pixels @ 035,021*/ 1, 0xB7, 
  /* RLE: 006 Pixels @ 036,021*/ 6, 0xFF, 
  /* RLE: 001 Pixels @ 042,021*/ 1, 0xB7, 
  /* RLE: 007 Pixels @ 043,021*/ 7, 0xE0, 
  /* ABS: 003 Pixels @ 050,021*/ 0, 3, 0xDF, 0xFF, 0xB7, 
  /* RLE: 053 Pixels @ 053,021*/ 53, 0xE0, 
  /* ABS: 003 Pixels @ 026,022*/ 0, 3, 0xFF, 0xFF, 0xB7, 
  /* RLE: 007 Pixels @ 029,022*/ 7, 0xE0, 
  /* ABS: 006 Pixels @ 036,022*/ 0, 6, 0xB7, 0xDF, 0xFF, 0xFF, 0xDF, 0xB7, 
  /* RLE: 008 Pixels @ 042,022*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 050,022*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 054 Pixels @ 052,022*/ 54, 0xE0, 
  /* ABS: 003 Pixels @ 026,023*/ 0, 3, 0xB7, 0xFF, 0xDF, 
  /* RLE: 020 Pixels @ 029,023*/ 20, 0xE0, 
  /* ABS: 003 Pixels @ 049,023*/ 0, 3, 0xDF, 0xFF, 0xD7, 
  /* RLE: 055 Pixels @ 052,023*/ 55, 0xE0, 
  /* ABS: 003 Pixels @ 027,024*/ 0, 3, 0xFF, 0xFF, 0xB7, 
  /* RLE: 018 Pixels @ 030,024*/ 18, 0xE0, 
  /* ABS: 003 Pixels @ 048,024*/ 0, 3, 0xB7, 0xFF, 0xFF, 
  /* RLE: 056 Pixels @ 051,024*/ 56, 0xE0, 
  /* ABS: 003 Pixels @ 027,025*/ 0, 3, 0xB7, 0xFF, 0xDF, 
  /* RLE: 018 Pixels @ 030,025*/ 18, 0xE0, 
  /* ABS: 003 Pixels @ 048,025*/ 0, 3, 0xDF, 0xFF, 0xB7, 
  /* RLE: 057 Pixels @ 051,025*/ 57, 0xE0, 
  /* ABS: 003 Pixels @ 028,026*/ 0, 3, 0xDF, 0xFF, 0xD7, 
  /* RLE: 016 Pixels @ 031,026*/ 16, 0xE0, 
  /* ABS: 003 Pixels @ 047,026*/ 0, 3, 0xD7, 0xFF, 0xFF, 
  /* RLE: 059 Pixels @ 050,026*/ 59, 0xE0, 
  /* ABS: 003 Pixels @ 029,027*/ 0, 3, 0xFF, 0xFF, 0xB7, 
  /* RLE: 015 Pixels @ 032,027*/ 15, 0xE0, 
  /* ABS: 002 Pixels @ 047,027*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 060 Pixels @ 049,027*/ 60, 0xE0, 
  /* ABS: 003 Pixels @ 029,028*/ 0, 3, 0xB7, 0xFF, 0xFF, 
  /* RLE: 014 Pixels @ 032,028*/ 14, 0xE0, 
  /* ABS: 003 Pixels @ 046,028*/ 0, 3, 0xFF, 0xFF, 0xB7, 
  /* RLE: 061 Pixels @ 049,028*/ 61, 0xE0, 
  /* ABS: 003 Pixels @ 030,029*/ 0, 3, 0xDF, 0xFF, 0xDF, 
  /* RLE: 012 Pixels @ 033,029*/ 12, 0xE0, 
  /* ABS: 003 Pixels @ 045,029*/ 0, 3, 0xDF, 0xFF, 0xDF, 
  /* RLE: 063 Pixels @ 048,029*/ 63, 0xE0, 
  /* ABS: 003 Pixels @ 031,030*/ 0, 3, 0xFF, 0xFF, 0xDF, 
  /* RLE: 010 Pixels @ 034,030*/ 10, 0xE0, 
  /* ABS: 003 Pixels @ 044,030*/ 0, 3, 0xD7, 0xFF, 0xFF, 
  /* RLE: 065 Pixels @ 047,030*/ 65, 0xE0, 
  /* ABS: 003 Pixels @ 032,031*/ 0, 3, 0xFF, 0xFF, 0xD7, 
  /* RLE: 008 Pixels @ 035,031*/ 8, 0xE0, 
  /* ABS: 003 Pixels @ 043,031*/ 0, 3, 0xD7, 0xFF, 0xFF, 
  /* RLE: 067 Pixels @ 046,031*/ 67, 0xE0, 
  /* ABS: 003 Pixels @ 033,032*/ 0, 3, 0xFF, 0xFF, 0xD7, 
  /* RLE: 006 Pixels @ 036,032*/ 6, 0xE0, 
  /* ABS: 004 Pixels @ 042,032*/ 0, 4, 0xD7, 0xFF, 0xFF, 0xB7, 
  /* RLE: 067 Pixels @ 046,032*/ 67, 0xE0, 
  /* ABS: 004 Pixels @ 033,033*/ 0, 4, 0xB7, 0xFF, 0xFF, 0xD7, 
  /* RLE: 004 Pixels @ 037,033*/ 4, 0xE0, 
  /* ABS: 004 Pixels @ 041,033*/ 0, 4, 0xB7, 0xFF, 0xFF, 0xB7, 
  /* RLE: 069 Pixels @ 045,033*/ 69, 0xE0, 
  /* ABS: 010 Pixels @ 034,034*/ 0, 10, 0xB7, 0xFF, 0xFF, 0xD7, 0xE0, 0xE0, 0xD7, 0xFF, 0xFF, 0xB7, 
  /* RLE: 071 Pixels @ 044,034*/ 71, 0xE0, 
  /* ABS: 008 Pixels @ 035,035*/ 0, 8, 0xB7, 0xFF, 0xFF, 0xDF, 0xD7, 0xFF, 0xFF, 0xB7, 
  /* RLE: 074 Pixels @ 043,035*/ 74, 0xE0, 
  /* RLE: 004 Pixels @ 037,036*/ 4, 0xFF, 
  /* RLE: 001 Pixels @ 041,036*/ 1, 0xB7, 
  /* RLE: 076 Pixels @ 042,036*/ 76, 0xE0, 
  /* ABS: 002 Pixels @ 038,037*/ 0, 2, 0xDF, 0xDF, 
  /* RLE: 318 Pixels @ 040,037*/ 254, 0xE0, 64, 0xE0, 
  /* ABS: 003 Pixels @ 038,041*/ 0, 3, 0x4F, 0xD7, 0x4F, 
  /* RLE: 076 Pixels @ 041,041*/ 76, 0xE0, 
  /* ABS: 005 Pixels @ 037,042*/ 0, 5, 0x97, 0xFF, 0xFF, 0xFF, 0x97, 
  /* RLE: 074 Pixels @ 042,042*/ 74, 0xE0, 
  /* RLE: 001 Pixels @ 036,043*/ 1, 0x97, 
  /* RLE: 005 Pixels @ 037,043*/ 5, 0xFF, 
  /* RLE: 001 Pixels @ 042,043*/ 1, 0x97, 
  /* RLE: 073 Pixels @ 043,043*/ 73, 0xE0, 
  /* RLE: 001 Pixels @ 036,044*/ 1, 0xDF, 
  /* RLE: 005 Pixels @ 037,044*/ 5, 0xFF, 
  /* RLE: 001 Pixels @ 042,044*/ 1, 0xDF, 
  /* RLE: 073 Pixels @ 043,044*/ 73, 0xE0, 
  /* RLE: 001 Pixels @ 036,045*/ 1, 0x97, 
  /* RLE: 005 Pixels @ 037,045*/ 5, 0xFF, 
  /* RLE: 001 Pixels @ 042,045*/ 1, 0x97, 
  /* RLE: 074 Pixels @ 043,045*/ 74, 0xE0, 
  /* ABS: 005 Pixels @ 037,046*/ 0, 5, 0x97, 0xFF, 0xFF, 0xFF, 0x97, 
  /* RLE: 076 Pixels @ 042,046*/ 76, 0xE0, 
  /* ABS: 003 Pixels @ 038,047*/ 0, 3, 0x97, 0xD7, 0x97, 
  /* RLE: 199 Pixels @ 041,047*/ 199, 0xE0, 


  0};  /* 623 for 4000 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmbmp_extru = {
  80, /* XSize */
  50, /* YSize */
  80, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acbmp_extru,  /* Pointer to picture data (indices) */
  &Palbmp_extru  /* Pointer to palette */
 ,GUI_DRAW_RLE8
};

/* *** End of file *** */
