/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: bmp_extru2
* Dimensions:  80 * 50
* NumColors:   256
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsbmp_extru2[] = {
     0x000000,0x000024,0x000048,0x00006D
    ,0x000091,0x0000B6,0x0000DA,0x0000FF
    ,0x005500,0x005524,0x005548,0x00556D
    ,0x005591,0x0055B6,0x0055DA,0x0055FF
    ,0x00AA00,0x00AA24,0x00AA48,0x00AA6D
    ,0x00AA91,0x00AAB6,0x00AADA,0x00AAFF
    ,0x00FF00,0x00FF24,0x00FF48,0x00FF6D
    ,0x00FF91,0x00FFB6,0x00FFDA,0x00FFFF
    ,0x240000,0x240024,0x240048,0x24006D
    ,0x240091,0x2400B6,0x2400DA,0x2400FF
    ,0x245500,0x245524,0x245548,0x24556D
    ,0x245591,0x2455B6,0x2455DA,0x2455FF
    ,0x24AA00,0x24AA24,0x24AA48,0x24AA6D
    ,0x24AA91,0x24AAB6,0x24AADA,0x24AAFF
    ,0x24FF00,0x24FF24,0x24FF48,0x24FF6D
    ,0x24FF91,0x24FFB6,0x24FFDA,0x24FFFF
    ,0x480000,0x480024,0x480048,0x48006D
    ,0x480091,0x4800B6,0x4800DA,0x4800FF
    ,0x485500,0x485524,0x485548,0x48556D
    ,0x485591,0x4855B6,0x4855DA,0x4855FF
    ,0x48AA00,0x48AA24,0x48AA48,0x48AA6D
    ,0x48AA91,0x48AAB6,0x48AADA,0x48AAFF
    ,0x48FF00,0x48FF24,0x48FF48,0x48FF6D
    ,0x48FF91,0x48FFB6,0x48FFDA,0x48FFFF
    ,0x6D0000,0x6D0024,0x6D0048,0x6D006D
    ,0x6D0091,0x6D00B6,0x6D00DA,0x6D00FF
    ,0x6D5500,0x6D5524,0x6D5548,0x6D556D
    ,0x6D5591,0x6D55B6,0x6D55DA,0x6D55FF
    ,0x6DAA00,0x6DAA24,0x6DAA48,0x6DAA6D
    ,0x6DAA91,0x6DAAB6,0x6DAADA,0x6DAAFF
    ,0x6DFF00,0x6DFF24,0x6DFF48,0x6DFF6D
    ,0x6DFF91,0x6DFFB6,0x6DFFDA,0x6DFFFF
    ,0x910000,0x910024,0x910048,0x91006D
    ,0x910091,0x9100B6,0x9100DA,0x9100FF
    ,0x915500,0x915524,0x915548,0x91556D
    ,0x915591,0x9155B6,0x9155DA,0x9155FF
    ,0x91AA00,0x91AA24,0x91AA48,0x91AA6D
    ,0x91AA91,0x91AAB6,0x91AADA,0x91AAFF
    ,0x91FF00,0x91FF24,0x91FF48,0x91FF6D
    ,0x91FF91,0x91FFB6,0x91FFDA,0x91FFFF
    ,0xB60000,0xB60024,0xB60048,0xB6006D
    ,0xB60091,0xB600B6,0xB600DA,0xB600FF
    ,0xB65500,0xB65524,0xB65548,0xB6556D
    ,0xB65591,0xB655B6,0xB655DA,0xB655FF
    ,0xB6AA00,0xB6AA24,0xB6AA48,0xB6AA6D
    ,0xB6AA91,0xB6AAB6,0xB6AADA,0xB6AAFF
    ,0xB6FF00,0xB6FF24,0xB6FF48,0xB6FF6D
    ,0xB6FF91,0xB6FFB6,0xB6FFDA,0xB6FFFF
    ,0xDA0000,0xDA0024,0xDA0048,0xDA006D
    ,0xDA0091,0xDA00B6,0xDA00DA,0xDA00FF
    ,0xDA5500,0xDA5524,0xDA5548,0xDA556D
    ,0xDA5591,0xDA55B6,0xDA55DA,0xDA55FF
    ,0xDAAA00,0xDAAA24,0xDAAA48,0xDAAA6D
    ,0xDAAA91,0xDAAAB6,0xDAAADA,0xDAAAFF
    ,0xDAFF00,0xDAFF24,0xDAFF48,0xDAFF6D
    ,0xDAFF91,0xDAFFB6,0xDAFFDA,0xDAFFFF
    ,0xFF0000,0xFF0024,0xFF0048,0xFF006D
    ,0xFF0091,0xFF00B6,0xFF00DA,0xFF00FF
    ,0xFF5500,0xFF5524,0xFF5548,0xFF556D
    ,0xFF5591,0xFF55B6,0xFF55DA,0xFF55FF
    ,0xFFAA00,0xFFAA24,0xFFAA48,0xFFAA6D
    ,0xFFAA91,0xFFAAB6,0xFFAADA,0xFFAAFF
    ,0xFFFF00,0xFFFF24,0xFFFF48,0xFFFF6D
    ,0xFFFF91,0xFFFFB6,0xFFFFDA,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palbmp_extru2 = {
  256,	/* number of entries */
  0, 	/* No transparency */
  &Colorsbmp_extru2[0]
};

static GUI_CONST_STORAGE unsigned char acbmp_extru2[] = {
  /* RLE: 744 Pixels @ 000,000*/ 254, 0xE0, 254, 0xE0, 236, 0xE0, 
  /* RLE: 032 Pixels @ 024,009*/ 32, 0xFF, 
  /* RLE: 001 Pixels @ 056,009*/ 1, 0xE1, 
  /* RLE: 047 Pixels @ 057,009*/ 47, 0xE0, 
  /* RLE: 032 Pixels @ 024,010*/ 32, 0xFF, 
  /* RLE: 001 Pixels @ 056,010*/ 1, 0xE1, 
  /* RLE: 047 Pixels @ 057,010*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,011*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 026,011*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 034,011*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 036,011*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 044,011*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 046,011*/ 8, 0xE0, 
  /* ABS: 003 Pixels @ 054,011*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,011*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,012*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 026,012*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 034,012*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 036,012*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 044,012*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 046,012*/ 8, 0xE0, 
  /* ABS: 003 Pixels @ 054,012*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,012*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,013*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 026,013*/ 8, 0xE0, 
  /* ABS: 012 Pixels @ 034,013*/ 0, 12, 0xFF, 0xFF, 0xE0, 0xE0, 0xE0, 0xFF, 0xFF, 0xFF, 0xE0, 0xE0, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 046,013*/ 8, 0xE0, 
  /* ABS: 003 Pixels @ 054,013*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,013*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,014*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 026,014*/ 8, 0xE0, 
  /* ABS: 012 Pixels @ 034,014*/ 0, 12, 0xFF, 0xFF, 0xE0, 0xE0, 0xFF, 0xE0, 0xE0, 0xE0, 0xFF, 0xE0, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 046,014*/ 8, 0xE0, 
  /* ABS: 003 Pixels @ 054,014*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,014*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,015*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 026,015*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 034,015*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 006 Pixels @ 036,015*/ 6, 0xE0, 
  /* ABS: 004 Pixels @ 042,015*/ 0, 4, 0xFF, 0xE0, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 046,015*/ 8, 0xE0, 
  /* ABS: 003 Pixels @ 054,015*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,015*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,016*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 026,016*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 034,016*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 036,016*/ 5, 0xE0, 
  /* ABS: 005 Pixels @ 041,016*/ 0, 5, 0xFF, 0xE0, 0xE0, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 046,016*/ 8, 0xE0, 
  /* ABS: 003 Pixels @ 054,016*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,016*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,017*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 026,017*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 034,017*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 036,017*/ 4, 0xE0, 
  /* ABS: 006 Pixels @ 040,017*/ 0, 6, 0xFF, 0xE0, 0xE0, 0xE0, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 046,017*/ 8, 0xE0, 
  /* ABS: 003 Pixels @ 054,017*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,017*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,018*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 026,018*/ 8, 0xE0, 
  /* ABS: 006 Pixels @ 034,018*/ 0, 6, 0xFF, 0xFF, 0xE0, 0xE0, 0xE0, 0xFF, 
  /* RLE: 004 Pixels @ 040,018*/ 4, 0xE0, 
  /* ABS: 002 Pixels @ 044,018*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 046,018*/ 8, 0xE0, 
  /* ABS: 003 Pixels @ 054,018*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,018*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,019*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 026,019*/ 8, 0xE0, 
  /* ABS: 005 Pixels @ 034,019*/ 0, 5, 0xFF, 0xFF, 0xE0, 0xE0, 0xFF, 
  /* RLE: 005 Pixels @ 039,019*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 044,019*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 046,019*/ 8, 0xE0, 
  /* ABS: 003 Pixels @ 054,019*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,019*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,020*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 026,020*/ 8, 0xE0, 
  /* ABS: 004 Pixels @ 034,020*/ 0, 4, 0xFF, 0xFF, 0xE0, 0xE0, 
  /* RLE: 005 Pixels @ 038,020*/ 5, 0xFF, 
  /* ABS: 003 Pixels @ 043,020*/ 0, 3, 0xE0, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 046,020*/ 8, 0xE0, 
  /* ABS: 003 Pixels @ 054,020*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,020*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,021*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 026,021*/ 8, 0xE0, 
  /* RLE: 003 Pixels @ 034,021*/ 3, 0xFF, 
  /* RLE: 006 Pixels @ 037,021*/ 6, 0xE0, 
  /* RLE: 003 Pixels @ 043,021*/ 3, 0xFF, 
  /* RLE: 008 Pixels @ 046,021*/ 8, 0xE0, 
  /* ABS: 003 Pixels @ 054,021*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,021*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,022*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 026,022*/ 8, 0xE0, 
  /* ABS: 004 Pixels @ 034,022*/ 0, 4, 0xE1, 0xFF, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 038,022*/ 4, 0xE0, 
  /* RLE: 003 Pixels @ 042,022*/ 3, 0xFF, 
  /* RLE: 009 Pixels @ 045,022*/ 9, 0xE0, 
  /* ABS: 003 Pixels @ 054,022*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,022*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,023*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 009 Pixels @ 026,023*/ 9, 0xE0, 
  /* ABS: 009 Pixels @ 035,023*/ 0, 9, 0xE1, 0xFF, 0xFF, 0xFF, 0xE0, 0xE0, 0xFF, 0xFF, 0xFF, 
  /* RLE: 010 Pixels @ 044,023*/ 10, 0xE0, 
  /* ABS: 003 Pixels @ 054,023*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,023*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,024*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 026,024*/ 11, 0xE0, 
  /* RLE: 006 Pixels @ 037,024*/ 6, 0xFF, 
  /* RLE: 011 Pixels @ 043,024*/ 11, 0xE0, 
  /* ABS: 003 Pixels @ 054,024*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,024*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,025*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 012 Pixels @ 026,025*/ 12, 0xE0, 
  /* RLE: 004 Pixels @ 038,025*/ 4, 0xFF, 
  /* RLE: 012 Pixels @ 042,025*/ 12, 0xE0, 
  /* ABS: 003 Pixels @ 054,025*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,025*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,026*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 013 Pixels @ 026,026*/ 13, 0xE0, 
  /* ABS: 002 Pixels @ 039,026*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 013 Pixels @ 041,026*/ 13, 0xE0, 
  /* ABS: 003 Pixels @ 054,026*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,026*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,027*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 013 Pixels @ 026,027*/ 13, 0xE0, 
  /* ABS: 002 Pixels @ 039,027*/ 0, 2, 0xE1, 0xEA, 
  /* RLE: 013 Pixels @ 041,027*/ 13, 0xE0, 
  /* ABS: 003 Pixels @ 054,027*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,027*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,028*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 013 Pixels @ 026,028*/ 13, 0xE0, 
  /* ABS: 003 Pixels @ 039,028*/ 0, 3, 0xE1, 0xFF, 0xFF, 
  /* RLE: 012 Pixels @ 042,028*/ 12, 0xE0, 
  /* ABS: 003 Pixels @ 054,028*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,028*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,029*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 014 Pixels @ 026,029*/ 14, 0xE0, 
  /* ABS: 004 Pixels @ 040,029*/ 0, 4, 0xE1, 0xE0, 0xFF, 0xFF, 
  /* RLE: 010 Pixels @ 044,029*/ 10, 0xE0, 
  /* ABS: 003 Pixels @ 054,029*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,029*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,030*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 018 Pixels @ 026,030*/ 18, 0xE0, 
  /* ABS: 002 Pixels @ 044,030*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 046,030*/ 8, 0xE0, 
  /* ABS: 003 Pixels @ 054,030*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,030*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,031*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 020 Pixels @ 026,031*/ 20, 0xE0, 
  /* RLE: 001 Pixels @ 046,031*/ 1, 0xFF, 
  /* RLE: 007 Pixels @ 047,031*/ 7, 0xE0, 
  /* ABS: 003 Pixels @ 054,031*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,031*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,032*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 020 Pixels @ 026,032*/ 20, 0xE0, 
  /* RLE: 001 Pixels @ 046,032*/ 1, 0xFF, 
  /* RLE: 007 Pixels @ 047,032*/ 7, 0xE0, 
  /* ABS: 003 Pixels @ 054,032*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,032*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,033*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 018 Pixels @ 026,033*/ 18, 0xE0, 
  /* ABS: 002 Pixels @ 044,033*/ 0, 2, 0xE1, 0xFF, 
  /* RLE: 008 Pixels @ 046,033*/ 8, 0xE0, 
  /* ABS: 003 Pixels @ 054,033*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,033*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,034*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 017 Pixels @ 026,034*/ 17, 0xE0, 
  /* ABS: 002 Pixels @ 043,034*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 009 Pixels @ 045,034*/ 9, 0xE0, 
  /* ABS: 003 Pixels @ 054,034*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,034*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,035*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 015 Pixels @ 026,035*/ 15, 0xE0, 
  /* ABS: 003 Pixels @ 041,035*/ 0, 3, 0xE1, 0xFF, 0xFF, 
  /* RLE: 010 Pixels @ 044,035*/ 10, 0xE0, 
  /* ABS: 003 Pixels @ 054,035*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,035*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,036*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 014 Pixels @ 026,036*/ 14, 0xE0, 
  /* ABS: 003 Pixels @ 040,036*/ 0, 3, 0xE1, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 043,036*/ 11, 0xE0, 
  /* ABS: 003 Pixels @ 054,036*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,036*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,037*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 013 Pixels @ 026,037*/ 13, 0xE0, 
  /* ABS: 004 Pixels @ 039,037*/ 0, 4, 0xFF, 0xFF, 0xE0, 0xE1, 
  /* RLE: 011 Pixels @ 043,037*/ 11, 0xE0, 
  /* ABS: 003 Pixels @ 054,037*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,037*/ 47, 0xE0, 
  /* ABS: 002 Pixels @ 024,038*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 028 Pixels @ 026,038*/ 28, 0xE0, 
  /* ABS: 003 Pixels @ 054,038*/ 0, 3, 0xFF, 0xFF, 0xE1, 
  /* RLE: 047 Pixels @ 057,038*/ 47, 0xE0, 
  /* RLE: 032 Pixels @ 024,039*/ 32, 0xFF, 
  /* RLE: 001 Pixels @ 056,039*/ 1, 0xE1, 
  /* RLE: 047 Pixels @ 057,039*/ 47, 0xE0, 
  /* RLE: 032 Pixels @ 024,040*/ 32, 0xFF, 
  /* RLE: 001 Pixels @ 056,040*/ 1, 0xE1, 
  /* RLE: 047 Pixels @ 057,040*/ 47, 0xE0, 
  /* RLE: 032 Pixels @ 024,041*/ 32, 0xE1, 
  /* RLE: 664 Pixels @ 056,041*/ 254, 0xE0, 254, 0xE0, 156, 0xE0, 


  0};  /* 665 for 4000 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmbmp_extru2 = {
  80, /* XSize */
  50, /* YSize */
  80, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acbmp_extru2,  /* Pointer to picture data (indices) */
  &Palbmp_extru2  /* Pointer to palette */
 ,GUI_DRAW_RLE8
};

/* *** End of file *** */
