/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: bmp_add
* Dimensions:  80 * 50
* NumColors:   256
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsbmp_add[] = {
     0x000000,0x000024,0x000048,0x00006D
    ,0x000091,0x0000B6,0x0000DA,0x0000FF
    ,0x005500,0x005524,0x005548,0x00556D
    ,0x005591,0x0055B6,0x0055DA,0x0055FF
    ,0x00AA00,0x00AA24,0x00AA48,0x00AA6D
    ,0x00AA91,0x00AAB6,0x00AADA,0x00AAFF
    ,0x00FF00,0x00FF24,0x00FF48,0x00FF6D
    ,0x00FF91,0x00FFB6,0x00FFDA,0x00FFFF
    ,0x240000,0x240024,0x240048,0x24006D
    ,0x240091,0x2400B6,0x2400DA,0x2400FF
    ,0x245500,0x245524,0x245548,0x24556D
    ,0x245591,0x2455B6,0x2455DA,0x2455FF
    ,0x24AA00,0x24AA24,0x24AA48,0x24AA6D
    ,0x24AA91,0x24AAB6,0x24AADA,0x24AAFF
    ,0x24FF00,0x24FF24,0x24FF48,0x24FF6D
    ,0x24FF91,0x24FFB6,0x24FFDA,0x24FFFF
    ,0x480000,0x480024,0x480048,0x48006D
    ,0x480091,0x4800B6,0x4800DA,0x4800FF
    ,0x485500,0x485524,0x485548,0x48556D
    ,0x485591,0x4855B6,0x4855DA,0x4855FF
    ,0x48AA00,0x48AA24,0x48AA48,0x48AA6D
    ,0x48AA91,0x48AAB6,0x48AADA,0x48AAFF
    ,0x48FF00,0x48FF24,0x48FF48,0x48FF6D
    ,0x48FF91,0x48FFB6,0x48FFDA,0x48FFFF
    ,0x6D0000,0x6D0024,0x6D0048,0x6D006D
    ,0x6D0091,0x6D00B6,0x6D00DA,0x6D00FF
    ,0x6D5500,0x6D5524,0x6D5548,0x6D556D
    ,0x6D5591,0x6D55B6,0x6D55DA,0x6D55FF
    ,0x6DAA00,0x6DAA24,0x6DAA48,0x6DAA6D
    ,0x6DAA91,0x6DAAB6,0x6DAADA,0x6DAAFF
    ,0x6DFF00,0x6DFF24,0x6DFF48,0x6DFF6D
    ,0x6DFF91,0x6DFFB6,0x6DFFDA,0x6DFFFF
    ,0x910000,0x910024,0x910048,0x91006D
    ,0x910091,0x9100B6,0x9100DA,0x9100FF
    ,0x915500,0x915524,0x915548,0x91556D
    ,0x915591,0x9155B6,0x9155DA,0x9155FF
    ,0x91AA00,0x91AA24,0x91AA48,0x91AA6D
    ,0x91AA91,0x91AAB6,0x91AADA,0x91AAFF
    ,0x91FF00,0x91FF24,0x91FF48,0x91FF6D
    ,0x91FF91,0x91FFB6,0x91FFDA,0x91FFFF
    ,0xB60000,0xB60024,0xB60048,0xB6006D
    ,0xB60091,0xB600B6,0xB600DA,0xB600FF
    ,0xB65500,0xB65524,0xB65548,0xB6556D
    ,0xB65591,0xB655B6,0xB655DA,0xB655FF
    ,0xB6AA00,0xB6AA24,0xB6AA48,0xB6AA6D
    ,0xB6AA91,0xB6AAB6,0xB6AADA,0xB6AAFF
    ,0xB6FF00,0xB6FF24,0xB6FF48,0xB6FF6D
    ,0xB6FF91,0xB6FFB6,0xB6FFDA,0xB6FFFF
    ,0xDA0000,0xDA0024,0xDA0048,0xDA006D
    ,0xDA0091,0xDA00B6,0xDA00DA,0xDA00FF
    ,0xDA5500,0xDA5524,0xDA5548,0xDA556D
    ,0xDA5591,0xDA55B6,0xDA55DA,0xDA55FF
    ,0xDAAA00,0xDAAA24,0xDAAA48,0xDAAA6D
    ,0xDAAA91,0xDAAAB6,0xDAAADA,0xDAAAFF
    ,0xDAFF00,0xDAFF24,0xDAFF48,0xDAFF6D
    ,0xDAFF91,0xDAFFB6,0xDAFFDA,0xDAFFFF
    ,0xFF0000,0xFF0024,0xFF0048,0xFF006D
    ,0xFF0091,0xFF00B6,0xFF00DA,0xFF00FF
    ,0xFF5500,0xFF5524,0xFF5548,0xFF556D
    ,0xFF5591,0xFF55B6,0xFF55DA,0xFF55FF
    ,0xFFAA00,0xFFAA24,0xFFAA48,0xFFAA6D
    ,0xFFAA91,0xFFAAB6,0xFFAADA,0xFFAAFF
    ,0xFFFF00,0xFFFF24,0xFFFF48,0xFFFF6D
    ,0xFFFF91,0xFFFFB6,0xFFFFDA,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palbmp_add = {
  256,	/* number of entries */
  0, 	/* No transparency */
  &Colorsbmp_add[0]
};

static GUI_CONST_STORAGE unsigned char acbmp_add[] = {
  /* RLE: 037 Pixels @ 000,000*/ 37, 0xE0, 
  /* ABS: 006 Pixels @ 037,000*/ 0, 6, 0xFE, 0xFF, 0xFF, 0xFF, 0xFE, 0xFE, 
  /* RLE: 070 Pixels @ 043,000*/ 70, 0xE0, 
  /* RLE: 014 Pixels @ 033,001*/ 14, 0xFF, 
  /* RLE: 063 Pixels @ 047,001*/ 63, 0xE0, 
  /* RLE: 020 Pixels @ 030,002*/ 20, 0xFF, 
  /* RLE: 058 Pixels @ 050,002*/ 58, 0xE0, 
  /* RLE: 021 Pixels @ 028,003*/ 21, 0xFF, 
  /* ABS: 003 Pixels @ 049,003*/ 0, 3, 0xDF, 0xFF, 0xFF, 
  /* RLE: 054 Pixels @ 052,003*/ 54, 0xE0, 
  /* RLE: 001 Pixels @ 026,004*/ 1, 0xFE, 
  /* RLE: 026 Pixels @ 027,004*/ 26, 0xFF, 
  /* RLE: 001 Pixels @ 053,004*/ 1, 0xFE, 
  /* RLE: 051 Pixels @ 054,004*/ 51, 0xE0, 
  /* RLE: 030 Pixels @ 025,005*/ 30, 0xFF, 
  /* RLE: 049 Pixels @ 055,005*/ 49, 0xE0, 
  /* RLE: 032 Pixels @ 024,006*/ 32, 0xFF, 
  /* RLE: 047 Pixels @ 056,006*/ 47, 0xE0, 
  /* RLE: 034 Pixels @ 023,007*/ 34, 0xFF, 
  /* RLE: 045 Pixels @ 057,007*/ 45, 0xE0, 
  /* RLE: 036 Pixels @ 022,008*/ 36, 0xFF, 
  /* RLE: 043 Pixels @ 058,008*/ 43, 0xE0, 
  /* ABS: 002 Pixels @ 021,009*/ 0, 2, 0xFF, 0xDF, 
  /* RLE: 036 Pixels @ 023,009*/ 36, 0xFF, 
  /* RLE: 041 Pixels @ 059,009*/ 41, 0xE0, 
  /* RLE: 019 Pixels @ 020,010*/ 19, 0xFF, 
  /* ABS: 002 Pixels @ 039,010*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 019 Pixels @ 041,010*/ 19, 0xFF, 
  /* RLE: 039 Pixels @ 060,010*/ 39, 0xE0, 
  /* RLE: 001 Pixels @ 019,011*/ 1, 0xFE, 
  /* RLE: 019 Pixels @ 020,011*/ 19, 0xFF, 
  /* ABS: 002 Pixels @ 039,011*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 019 Pixels @ 041,011*/ 19, 0xFF, 
  /* RLE: 001 Pixels @ 060,011*/ 1, 0xFE, 
  /* RLE: 038 Pixels @ 061,011*/ 38, 0xE0, 
  /* RLE: 020 Pixels @ 019,012*/ 20, 0xFF, 
  /* ABS: 002 Pixels @ 039,012*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 020 Pixels @ 041,012*/ 20, 0xFF, 
  /* RLE: 037 Pixels @ 061,012*/ 37, 0xE0, 
  /* RLE: 001 Pixels @ 018,013*/ 1, 0xFE, 
  /* RLE: 020 Pixels @ 019,013*/ 20, 0xFF, 
  /* ABS: 002 Pixels @ 039,013*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 021 Pixels @ 041,013*/ 21, 0xFF, 
  /* RLE: 036 Pixels @ 062,013*/ 36, 0xE0, 
  /* RLE: 021 Pixels @ 018,014*/ 21, 0xFF, 
  /* ABS: 002 Pixels @ 039,014*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 021 Pixels @ 041,014*/ 21, 0xFF, 
  /* RLE: 035 Pixels @ 062,014*/ 35, 0xE0, 
  /* RLE: 022 Pixels @ 017,015*/ 22, 0xFF, 
  /* ABS: 002 Pixels @ 039,015*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 022 Pixels @ 041,015*/ 22, 0xFF, 
  /* RLE: 034 Pixels @ 063,015*/ 34, 0xE0, 
  /* RLE: 022 Pixels @ 017,016*/ 22, 0xFF, 
  /* ABS: 002 Pixels @ 039,016*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 022 Pixels @ 041,016*/ 22, 0xFF, 
  /* RLE: 034 Pixels @ 063,016*/ 34, 0xE0, 
  /* RLE: 022 Pixels @ 017,017*/ 22, 0xFF, 
  /* ABS: 002 Pixels @ 039,017*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 022 Pixels @ 041,017*/ 22, 0xFF, 
  /* RLE: 001 Pixels @ 063,017*/ 1, 0xFE, 
  /* RLE: 032 Pixels @ 064,017*/ 32, 0xE0, 
  /* RLE: 023 Pixels @ 016,018*/ 23, 0xFF, 
  /* ABS: 002 Pixels @ 039,018*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 023 Pixels @ 041,018*/ 23, 0xFF, 
  /* RLE: 032 Pixels @ 064,018*/ 32, 0xE0, 
  /* RLE: 023 Pixels @ 016,019*/ 23, 0xFF, 
  /* ABS: 002 Pixels @ 039,019*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 023 Pixels @ 041,019*/ 23, 0xFF, 
  /* RLE: 032 Pixels @ 064,019*/ 32, 0xE0, 
  /* RLE: 023 Pixels @ 016,020*/ 23, 0xFF, 
  /* ABS: 002 Pixels @ 039,020*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 023 Pixels @ 041,020*/ 23, 0xFF, 
  /* RLE: 032 Pixels @ 064,020*/ 32, 0xE0, 
  /* RLE: 023 Pixels @ 016,021*/ 23, 0xFF, 
  /* ABS: 002 Pixels @ 039,021*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 023 Pixels @ 041,021*/ 23, 0xFF, 
  /* RLE: 032 Pixels @ 064,021*/ 32, 0xE0, 
  /* RLE: 023 Pixels @ 016,022*/ 23, 0xFF, 
  /* ABS: 002 Pixels @ 039,022*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 023 Pixels @ 041,022*/ 23, 0xFF, 
  /* RLE: 001 Pixels @ 064,022*/ 1, 0xFE, 
  /* RLE: 030 Pixels @ 065,022*/ 30, 0xE0, 
  /* RLE: 024 Pixels @ 015,023*/ 24, 0xFF, 
  /* ABS: 002 Pixels @ 039,023*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 024 Pixels @ 041,023*/ 24, 0xFF, 
  /* RLE: 030 Pixels @ 065,023*/ 30, 0xE0, 
  /* RLE: 010 Pixels @ 015,024*/ 10, 0xFF, 
  /* RLE: 030 Pixels @ 025,024*/ 30, 0xE0, 
  /* RLE: 010 Pixels @ 055,024*/ 10, 0xFF, 
  /* RLE: 030 Pixels @ 065,024*/ 30, 0xE0, 
  /* RLE: 010 Pixels @ 015,025*/ 10, 0xFF, 
  /* RLE: 030 Pixels @ 025,025*/ 30, 0xE0, 
  /* RLE: 010 Pixels @ 055,025*/ 10, 0xFF, 
  /* RLE: 030 Pixels @ 065,025*/ 30, 0xE0, 
  /* RLE: 001 Pixels @ 015,026*/ 1, 0xFE, 
  /* RLE: 019 Pixels @ 016,026*/ 19, 0xFF, 
  /* ABS: 006 Pixels @ 035,026*/ 0, 6, 0xDF, 0xFF, 0xFF, 0xFF, 0xE0, 0xE0, 
  /* RLE: 024 Pixels @ 041,026*/ 24, 0xFF, 
  /* RLE: 030 Pixels @ 065,026*/ 30, 0xE0, 
  /* RLE: 001 Pixels @ 015,027*/ 1, 0xFE, 
  /* RLE: 023 Pixels @ 016,027*/ 23, 0xFF, 
  /* ABS: 002 Pixels @ 039,027*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 023 Pixels @ 041,027*/ 23, 0xFF, 
  /* RLE: 001 Pixels @ 064,027*/ 1, 0xFE, 
  /* RLE: 031 Pixels @ 065,027*/ 31, 0xE0, 
  /* RLE: 023 Pixels @ 016,028*/ 23, 0xFF, 
  /* ABS: 002 Pixels @ 039,028*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 023 Pixels @ 041,028*/ 23, 0xFF, 
  /* RLE: 032 Pixels @ 064,028*/ 32, 0xE0, 
  /* RLE: 023 Pixels @ 016,029*/ 23, 0xFF, 
  /* ABS: 002 Pixels @ 039,029*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 023 Pixels @ 041,029*/ 23, 0xFF, 
  /* RLE: 032 Pixels @ 064,029*/ 32, 0xE0, 
  /* RLE: 023 Pixels @ 016,030*/ 23, 0xFF, 
  /* ABS: 002 Pixels @ 039,030*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 023 Pixels @ 041,030*/ 23, 0xFF, 
  /* RLE: 032 Pixels @ 064,030*/ 32, 0xE0, 
  /* RLE: 023 Pixels @ 016,031*/ 23, 0xFF, 
  /* ABS: 002 Pixels @ 039,031*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 023 Pixels @ 041,031*/ 23, 0xFF, 
  /* RLE: 033 Pixels @ 064,031*/ 33, 0xE0, 
  /* RLE: 022 Pixels @ 017,032*/ 22, 0xFF, 
  /* ABS: 002 Pixels @ 039,032*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 022 Pixels @ 041,032*/ 22, 0xFF, 
  /* RLE: 034 Pixels @ 063,032*/ 34, 0xE0, 
  /* RLE: 022 Pixels @ 017,033*/ 22, 0xFF, 
  /* ABS: 002 Pixels @ 039,033*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 022 Pixels @ 041,033*/ 22, 0xFF, 
  /* RLE: 034 Pixels @ 063,033*/ 34, 0xE0, 
  /* RLE: 022 Pixels @ 017,034*/ 22, 0xFF, 
  /* ABS: 002 Pixels @ 039,034*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 021 Pixels @ 041,034*/ 21, 0xFF, 
  /* RLE: 001 Pixels @ 062,034*/ 1, 0xFE, 
  /* RLE: 035 Pixels @ 063,034*/ 35, 0xE0, 
  /* RLE: 021 Pixels @ 018,035*/ 21, 0xFF, 
  /* ABS: 002 Pixels @ 039,035*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 020 Pixels @ 041,035*/ 20, 0xFF, 
  /* RLE: 001 Pixels @ 061,035*/ 1, 0xDF, 
  /* RLE: 036 Pixels @ 062,035*/ 36, 0xE0, 
  /* RLE: 017 Pixels @ 018,036*/ 17, 0xFF, 
  /* ABS: 006 Pixels @ 035,036*/ 0, 6, 0xDF, 0xFF, 0xFF, 0xFF, 0xE0, 0xE0, 
  /* RLE: 021 Pixels @ 041,036*/ 21, 0xFF, 
  /* RLE: 037 Pixels @ 062,036*/ 37, 0xE0, 
  /* RLE: 020 Pixels @ 019,037*/ 20, 0xFF, 
  /* ABS: 002 Pixels @ 039,037*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 020 Pixels @ 041,037*/ 20, 0xFF, 
  /* RLE: 038 Pixels @ 061,037*/ 38, 0xE0, 
  /* RLE: 001 Pixels @ 019,038*/ 1, 0xFE, 
  /* RLE: 019 Pixels @ 020,038*/ 19, 0xFF, 
  /* ABS: 002 Pixels @ 039,038*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 019 Pixels @ 041,038*/ 19, 0xFF, 
  /* RLE: 001 Pixels @ 060,038*/ 1, 0xFE, 
  /* RLE: 039 Pixels @ 061,038*/ 39, 0xE0, 
  /* RLE: 019 Pixels @ 020,039*/ 19, 0xFF, 
  /* ABS: 002 Pixels @ 039,039*/ 0, 2, 0xE0, 0xE0, 
  /* RLE: 019 Pixels @ 041,039*/ 19, 0xFF, 
  /* RLE: 041 Pixels @ 060,039*/ 41, 0xE0, 
  /* RLE: 038 Pixels @ 021,040*/ 38, 0xFF, 
  /* RLE: 043 Pixels @ 059,040*/ 43, 0xE0, 
  /* RLE: 036 Pixels @ 022,041*/ 36, 0xFF, 
  /* RLE: 045 Pixels @ 058,041*/ 45, 0xE0, 
  /* RLE: 034 Pixels @ 023,042*/ 34, 0xFF, 
  /* RLE: 047 Pixels @ 057,042*/ 47, 0xE0, 
  /* RLE: 032 Pixels @ 024,043*/ 32, 0xFF, 
  /* RLE: 001 Pixels @ 056,043*/ 1, 0xDE, 
  /* RLE: 048 Pixels @ 057,043*/ 48, 0xE0, 
  /* RLE: 027 Pixels @ 025,044*/ 27, 0xFF, 
  /* ABS: 003 Pixels @ 052,044*/ 0, 3, 0xDF, 0xFF, 0xFF, 
  /* RLE: 051 Pixels @ 055,044*/ 51, 0xE0, 
  /* RLE: 001 Pixels @ 026,045*/ 1, 0xFE, 
  /* RLE: 026 Pixels @ 027,045*/ 26, 0xFF, 
  /* RLE: 001 Pixels @ 053,045*/ 1, 0xFE, 
  /* RLE: 054 Pixels @ 054,045*/ 54, 0xE0, 
  /* RLE: 024 Pixels @ 028,046*/ 24, 0xFF, 
  /* RLE: 058 Pixels @ 052,046*/ 58, 0xE0, 
  /* RLE: 020 Pixels @ 030,047*/ 20, 0xFF, 
  /* RLE: 062 Pixels @ 050,047*/ 62, 0xE0, 
  /* RLE: 001 Pixels @ 032,048*/ 1, 0xFE, 
  /* RLE: 014 Pixels @ 033,048*/ 14, 0xFF, 
  /* RLE: 070 Pixels @ 047,048*/ 70, 0xE0, 
  /* RLE: 001 Pixels @ 037,049*/ 1, 0xFE, 
  /* RLE: 004 Pixels @ 038,049*/ 4, 0xFF, 
  /* RLE: 001 Pixels @ 042,049*/ 1, 0xFE, 
  /* RLE: 037 Pixels @ 043,049*/ 37, 0xE0, 


  0};  /* 446 for 4000 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmbmp_add = {
  80, /* XSize */
  50, /* YSize */
  80, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acbmp_add,  /* Pointer to picture data (indices) */
  &Palbmp_add  /* Pointer to palette */
 ,GUI_DRAW_RLE8
};

/* *** End of file *** */
