/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: bmp_zero
* Dimensions:  80 * 50
* NumColors:   256
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsbmp_zero[] = {
     0x000000,0x000024,0x000048,0x00006D
    ,0x000091,0x0000B6,0x0000DA,0x0000FF
    ,0x005500,0x005524,0x005548,0x00556D
    ,0x005591,0x0055B6,0x0055DA,0x0055FF
    ,0x00AA00,0x00AA24,0x00AA48,0x00AA6D
    ,0x00AA91,0x00AAB6,0x00AADA,0x00AAFF
    ,0x00FF00,0x00FF24,0x00FF48,0x00FF6D
    ,0x00FF91,0x00FFB6,0x00FFDA,0x00FFFF
    ,0x240000,0x240024,0x240048,0x24006D
    ,0x240091,0x2400B6,0x2400DA,0x2400FF
    ,0x245500,0x245524,0x245548,0x24556D
    ,0x245591,0x2455B6,0x2455DA,0x2455FF
    ,0x24AA00,0x24AA24,0x24AA48,0x24AA6D
    ,0x24AA91,0x24AAB6,0x24AADA,0x24AAFF
    ,0x24FF00,0x24FF24,0x24FF48,0x24FF6D
    ,0x24FF91,0x24FFB6,0x24FFDA,0x24FFFF
    ,0x480000,0x480024,0x480048,0x48006D
    ,0x480091,0x4800B6,0x4800DA,0x4800FF
    ,0x485500,0x485524,0x485548,0x48556D
    ,0x485591,0x4855B6,0x4855DA,0x4855FF
    ,0x48AA00,0x48AA24,0x48AA48,0x48AA6D
    ,0x48AA91,0x48AAB6,0x48AADA,0x48AAFF
    ,0x48FF00,0x48FF24,0x48FF48,0x48FF6D
    ,0x48FF91,0x48FFB6,0x48FFDA,0x48FFFF
    ,0x6D0000,0x6D0024,0x6D0048,0x6D006D
    ,0x6D0091,0x6D00B6,0x6D00DA,0x6D00FF
    ,0x6D5500,0x6D5524,0x6D5548,0x6D556D
    ,0x6D5591,0x6D55B6,0x6D55DA,0x6D55FF
    ,0x6DAA00,0x6DAA24,0x6DAA48,0x6DAA6D
    ,0x6DAA91,0x6DAAB6,0x6DAADA,0x6DAAFF
    ,0x6DFF00,0x6DFF24,0x6DFF48,0x6DFF6D
    ,0x6DFF91,0x6DFFB6,0x6DFFDA,0x6DFFFF
    ,0x910000,0x910024,0x910048,0x91006D
    ,0x910091,0x9100B6,0x9100DA,0x9100FF
    ,0x915500,0x915524,0x915548,0x91556D
    ,0x915591,0x9155B6,0x9155DA,0x9155FF
    ,0x91AA00,0x91AA24,0x91AA48,0x91AA6D
    ,0x91AA91,0x91AAB6,0x91AADA,0x91AAFF
    ,0x91FF00,0x91FF24,0x91FF48,0x91FF6D
    ,0x91FF91,0x91FFB6,0x91FFDA,0x91FFFF
    ,0xB60000,0xB60024,0xB60048,0xB6006D
    ,0xB60091,0xB600B6,0xB600DA,0xB600FF
    ,0xB65500,0xB65524,0xB65548,0xB6556D
    ,0xB65591,0xB655B6,0xB655DA,0xB655FF
    ,0xB6AA00,0xB6AA24,0xB6AA48,0xB6AA6D
    ,0xB6AA91,0xB6AAB6,0xB6AADA,0xB6AAFF
    ,0xB6FF00,0xB6FF24,0xB6FF48,0xB6FF6D
    ,0xB6FF91,0xB6FFB6,0xB6FFDA,0xB6FFFF
    ,0xDA0000,0xDA0024,0xDA0048,0xDA006D
    ,0xDA0091,0xDA00B6,0xDA00DA,0xDA00FF
    ,0xDA5500,0xDA5524,0xDA5548,0xDA556D
    ,0xDA5591,0xDA55B6,0xDA55DA,0xDA55FF
    ,0xDAAA00,0xDAAA24,0xDAAA48,0xDAAA6D
    ,0xDAAA91,0xDAAAB6,0xDAAADA,0xDAAAFF
    ,0xDAFF00,0xDAFF24,0xDAFF48,0xDAFF6D
    ,0xDAFF91,0xDAFFB6,0xDAFFDA,0xDAFFFF
    ,0xFF0000,0xFF0024,0xFF0048,0xFF006D
    ,0xFF0091,0xFF00B6,0xFF00DA,0xFF00FF
    ,0xFF5500,0xFF5524,0xFF5548,0xFF556D
    ,0xFF5591,0xFF55B6,0xFF55DA,0xFF55FF
    ,0xFFAA00,0xFFAA24,0xFFAA48,0xFFAA6D
    ,0xFFAA91,0xFFAAB6,0xFFAADA,0xFFAAFF
    ,0xFFFF00,0xFFFF24,0xFFFF48,0xFFFF6D
    ,0xFFFF91,0xFFFFB6,0xFFFFDA,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palbmp_zero = {
  256,	/* number of entries */
  0, 	/* No transparency */
  &Colorsbmp_zero[0]
};

static GUI_CONST_STORAGE unsigned char acbmp_zero[] = {
  /* RLE: 519 Pixels @ 000,000*/ 254, 0xE0, 254, 0xE0, 11, 0xE0, 
  /* ABS: 002 Pixels @ 039,006*/ 0, 2, 0x4A, 0x4A, 
  /* RLE: 077 Pixels @ 041,006*/ 77, 0xE0, 
  /* ABS: 004 Pixels @ 038,007*/ 0, 4, 0x4A, 0xFF, 0xFF, 0x4A, 
  /* RLE: 075 Pixels @ 042,007*/ 75, 0xE0, 
  /* RLE: 001 Pixels @ 037,008*/ 1, 0x4A, 
  /* RLE: 004 Pixels @ 038,008*/ 4, 0xFF, 
  /* RLE: 001 Pixels @ 042,008*/ 1, 0x4A, 
  /* RLE: 073 Pixels @ 043,008*/ 73, 0xE0, 
  /* ABS: 008 Pixels @ 036,009*/ 0, 8, 0x4A, 0xFF, 0xFF, 0xE0, 0xE0, 0xFF, 0xFF, 0x4A, 
  /* RLE: 071 Pixels @ 044,009*/ 71, 0xE0, 
  /* ABS: 010 Pixels @ 035,010*/ 0, 10, 0x6B, 0xFF, 0xFF, 0xDE, 0xE0, 0xE0, 0xE0, 0xFF, 0xFF, 0x4A, 
  /* RLE: 069 Pixels @ 045,010*/ 69, 0xE0, 
  /* ABS: 004 Pixels @ 034,011*/ 0, 4, 0x6B, 0xFF, 0xFF, 0xD6, 
  /* RLE: 004 Pixels @ 038,011*/ 4, 0xE0, 
  /* ABS: 004 Pixels @ 042,011*/ 0, 4, 0xDE, 0xFF, 0xFF, 0x6B, 
  /* RLE: 067 Pixels @ 046,011*/ 67, 0xE0, 
  /* ABS: 004 Pixels @ 033,012*/ 0, 4, 0x6B, 0xFF, 0xFF, 0xD6, 
  /* RLE: 006 Pixels @ 037,012*/ 6, 0xE0, 
  /* ABS: 004 Pixels @ 043,012*/ 0, 4, 0xD6, 0xFF, 0xFF, 0x6B, 
  /* RLE: 065 Pixels @ 047,012*/ 65, 0xE0, 
  /* ABS: 004 Pixels @ 032,013*/ 0, 4, 0x6B, 0xFF, 0xFF, 0xB5, 
  /* RLE: 008 Pixels @ 036,013*/ 8, 0xE0, 
  /* ABS: 004 Pixels @ 044,013*/ 0, 4, 0xD6, 0xFF, 0xFF, 0x6B, 
  /* RLE: 063 Pixels @ 048,013*/ 63, 0xE0, 
  /* ABS: 004 Pixels @ 031,014*/ 0, 4, 0x6B, 0xFF, 0xFF, 0xB5, 
  /* RLE: 010 Pixels @ 035,014*/ 10, 0xE0, 
  /* ABS: 004 Pixels @ 045,014*/ 0, 4, 0xB5, 0xFF, 0xFF, 0x6B, 
  /* RLE: 061 Pixels @ 049,014*/ 61, 0xE0, 
  /* ABS: 004 Pixels @ 030,015*/ 0, 4, 0x94, 0xFF, 0xFF, 0xB5, 
  /* RLE: 012 Pixels @ 034,015*/ 12, 0xE0, 
  /* ABS: 004 Pixels @ 046,015*/ 0, 4, 0xB5, 0xFF, 0xFF, 0x94, 
  /* RLE: 059 Pixels @ 050,015*/ 59, 0xE0, 
  /* ABS: 004 Pixels @ 029,016*/ 0, 4, 0x94, 0xFF, 0xFF, 0xB5, 
  /* RLE: 014 Pixels @ 033,016*/ 14, 0xE0, 
  /* ABS: 004 Pixels @ 047,016*/ 0, 4, 0xB5, 0xFF, 0xFF, 0x94, 
  /* RLE: 057 Pixels @ 051,016*/ 57, 0xE0, 
  /* ABS: 004 Pixels @ 028,017*/ 0, 4, 0x94, 0xFF, 0xFF, 0xB5, 
  /* RLE: 016 Pixels @ 032,017*/ 16, 0xE0, 
  /* ABS: 004 Pixels @ 048,017*/ 0, 4, 0xB5, 0xFF, 0xFF, 0x94, 
  /* RLE: 055 Pixels @ 052,017*/ 55, 0xE0, 
  /* ABS: 004 Pixels @ 027,018*/ 0, 4, 0x94, 0xFF, 0xFF, 0x94, 
  /* RLE: 018 Pixels @ 031,018*/ 18, 0xE0, 
  /* ABS: 004 Pixels @ 049,018*/ 0, 4, 0x94, 0xFF, 0xFF, 0x94, 
  /* RLE: 053 Pixels @ 053,018*/ 53, 0xE0, 
  /* ABS: 004 Pixels @ 026,019*/ 0, 4, 0xB5, 0xFF, 0xFF, 0x94, 
  /* RLE: 020 Pixels @ 030,019*/ 20, 0xE0, 
  /* ABS: 004 Pixels @ 050,019*/ 0, 4, 0x94, 0xFF, 0xFF, 0xB5, 
  /* RLE: 051 Pixels @ 054,019*/ 51, 0xE0, 
  /* ABS: 004 Pixels @ 025,020*/ 0, 4, 0xB5, 0xFF, 0xFF, 0xFF, 
  /* RLE: 022 Pixels @ 029,020*/ 22, 0xE0, 
  /* RLE: 003 Pixels @ 051,020*/ 3, 0xFF, 
  /* RLE: 001 Pixels @ 054,020*/ 1, 0xB5, 
  /* RLE: 049 Pixels @ 055,020*/ 49, 0xE0, 
  /* RLE: 001 Pixels @ 024,021*/ 1, 0xB5, 
  /* RLE: 004 Pixels @ 025,021*/ 4, 0xFF, 
  /* RLE: 022 Pixels @ 029,021*/ 22, 0xE0, 
  /* RLE: 004 Pixels @ 051,021*/ 4, 0xFF, 
  /* RLE: 001 Pixels @ 055,021*/ 1, 0xB5, 
  /* RLE: 048 Pixels @ 056,021*/ 48, 0xE0, 
  /* ABS: 005 Pixels @ 024,022*/ 0, 5, 0xFF, 0xFF, 0x6B, 0xFF, 0xFF, 
  /* RLE: 022 Pixels @ 029,022*/ 22, 0xE0, 
  /* ABS: 005 Pixels @ 051,022*/ 0, 5, 0xFF, 0xFF, 0x6B, 0xFF, 0xFF, 
  /* RLE: 048 Pixels @ 056,022*/ 48, 0xE0, 
  /* ABS: 005 Pixels @ 024,023*/ 0, 5, 0x94, 0x94, 0xE0, 0xFF, 0xFF, 
  /* RLE: 022 Pixels @ 029,023*/ 22, 0xE0, 
  /* ABS: 005 Pixels @ 051,023*/ 0, 5, 0xFF, 0xFF, 0xE0, 0x94, 0x6B, 
  /* RLE: 051 Pixels @ 056,023*/ 51, 0xE0, 
  /* ABS: 002 Pixels @ 027,024*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 022 Pixels @ 029,024*/ 22, 0xE0, 
  /* ABS: 002 Pixels @ 051,024*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 054 Pixels @ 053,024*/ 54, 0xE0, 
  /* ABS: 002 Pixels @ 027,025*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 029,025*/ 5, 0xE0, 
  /* RLE: 001 Pixels @ 034,025*/ 1, 0x6B, 
  /* RLE: 010 Pixels @ 035,025*/ 10, 0xFF, 
  /* RLE: 001 Pixels @ 045,025*/ 1, 0x4A, 
  /* RLE: 005 Pixels @ 046,025*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 051,025*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 054 Pixels @ 053,025*/ 54, 0xE0, 
  /* ABS: 002 Pixels @ 027,026*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 029,026*/ 5, 0xE0, 
  /* RLE: 012 Pixels @ 034,026*/ 12, 0xFF, 
  /* RLE: 005 Pixels @ 046,026*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 051,026*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 054 Pixels @ 053,026*/ 54, 0xE0, 
  /* ABS: 002 Pixels @ 027,027*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 029,027*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 034,027*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 036,027*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 044,027*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 046,027*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 051,027*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 054 Pixels @ 053,027*/ 54, 0xE0, 
  /* ABS: 002 Pixels @ 027,028*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 029,028*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 034,028*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 036,028*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 044,028*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 046,028*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 051,028*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 054 Pixels @ 053,028*/ 54, 0xE0, 
  /* ABS: 002 Pixels @ 027,029*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 029,029*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 034,029*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 036,029*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 044,029*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 046,029*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 051,029*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 054 Pixels @ 053,029*/ 54, 0xE0, 
  /* ABS: 002 Pixels @ 027,030*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 029,030*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 034,030*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 036,030*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 044,030*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 046,030*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 051,030*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 054 Pixels @ 053,030*/ 54, 0xE0, 
  /* ABS: 002 Pixels @ 027,031*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 029,031*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 034,031*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 036,031*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 044,031*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 046,031*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 051,031*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 054 Pixels @ 053,031*/ 54, 0xE0, 
  /* ABS: 002 Pixels @ 027,032*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 029,032*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 034,032*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 036,032*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 044,032*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 046,032*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 051,032*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 054 Pixels @ 053,032*/ 54, 0xE0, 
  /* ABS: 002 Pixels @ 027,033*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 029,033*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 034,033*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 036,033*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 044,033*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 046,033*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 051,033*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 054 Pixels @ 053,033*/ 54, 0xE0, 
  /* ABS: 002 Pixels @ 027,034*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 029,034*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 034,034*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 036,034*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 044,034*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 046,034*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 051,034*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 054 Pixels @ 053,034*/ 54, 0xE0, 
  /* ABS: 002 Pixels @ 027,035*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 029,035*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 034,035*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 008 Pixels @ 036,035*/ 8, 0xE0, 
  /* ABS: 002 Pixels @ 044,035*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 046,035*/ 5, 0xE0, 
  /* ABS: 002 Pixels @ 051,035*/ 0, 2, 0xFF, 0xFF, 
  /* RLE: 054 Pixels @ 053,035*/ 54, 0xE0, 
  /* RLE: 009 Pixels @ 027,036*/ 9, 0xFF, 
  /* RLE: 008 Pixels @ 036,036*/ 8, 0xE0, 
  /* RLE: 009 Pixels @ 044,036*/ 9, 0xFF, 
  /* RLE: 054 Pixels @ 053,036*/ 54, 0xE0, 
  /* RLE: 001 Pixels @ 027,037*/ 1, 0x6B, 
  /* RLE: 007 Pixels @ 028,037*/ 7, 0xFF, 
  /* RLE: 001 Pixels @ 035,037*/ 1, 0x4A, 
  /* RLE: 008 Pixels @ 036,037*/ 8, 0xE0, 
  /* RLE: 001 Pixels @ 044,037*/ 1, 0x4A, 
  /* RLE: 007 Pixels @ 045,037*/ 7, 0xFF, 
  /* RLE: 001 Pixels @ 052,037*/ 1, 0x6B, 
  /* RLE: 987 Pixels @ 053,037*/ 254, 0xE0, 254, 0xE0, 254, 0xE0, 225, 0xE0, 


  0};  /* 554 for 4000 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmbmp_zero = {
  80, /* XSize */
  50, /* YSize */
  80, /* BytesPerLine */
  GUI_COMPRESS_RLE8, /* BitsPerPixel */
  acbmp_zero,  /* Pointer to picture data (indices) */
  &Palbmp_zero  /* Pointer to palette */
 ,GUI_DRAW_RLE8
};

/* *** End of file *** */
